const DB_NAME="wineshoppos_purchase_drafts_v1",DB_VERSION=1,DRAFT_STORE="purchase_drafts",KEY_STORE="crypto_keys",KEY_ID="purchase-draft-aes-key";
const reqPromise=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(DRAFT_STORE)){const s=db.createObjectStore(DRAFT_STORE,{keyPath:"id"});s.createIndex("updatedAt","updatedAt");}if(!db.objectStoreNames.contains(KEY_STORE))db.createObjectStore(KEY_STORE,{keyPath:"id"});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function key(){if(!globalThis.crypto?.subtle||typeof indexedDB==="undefined")throw new Error("Secure offline purchase drafts are unavailable in this browser.");const db=await openDb();try{const tx=db.transaction(KEY_STORE,"readwrite"),s=tx.objectStore(KEY_STORE),old=await reqPromise(s.get(KEY_ID));if(old?.key)return old.key;const k=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);s.put({id:KEY_ID,key:k});return k;}finally{db.close();}}
const b64=b=>{let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s);};const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function encrypt(payload){const k=await key(),iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(payload)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},k,plain);return{iv:b64(iv),cipher:b64(new Uint8Array(cipher))};}
async function decrypt(row){const k=await key(),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:bytes(row.iv)},k,bytes(row.cipher));return JSON.parse(new TextDecoder().decode(plain));}
export async function saveOfflinePurchaseDraft(id,payload){const enc=await encrypt(payload),db=await openDb();try{db.transaction(DRAFT_STORE,"readwrite").objectStore(DRAFT_STORE).put({id,updatedAt:new Date().toISOString(),...enc});}finally{db.close();}}
export async function loadOfflinePurchaseDraft(id){if(!id)return null;const db=await openDb();try{const row=await reqPromise(db.transaction(DRAFT_STORE,"readonly").objectStore(DRAFT_STORE).get(id));return row?{...row,payload:await decrypt(row)}:null;}finally{db.close();}}
export async function removeOfflinePurchaseDraft(id){if(!id)return;const db=await openDb();try{db.transaction(DRAFT_STORE,"readwrite").objectStore(DRAFT_STORE).delete(id);}finally{db.close();}}
export async function countOfflinePurchaseDrafts(){const db=await openDb();try{return await reqPromise(db.transaction(DRAFT_STORE,"readonly").objectStore(DRAFT_STORE).count());}finally{db.close();}}
