import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const r=p=>fs.readFileSync(p,"utf8"),badge=r("src/components/EnvironmentBadge.jsx"),automation=r("src/pages/AutomationHub.jsx"),preview=r("src/components/OcrProductImagePreview.jsx"),form=r("src/components/ProductForm.jsx"),edit=r("src/pages/EditProduct.jsx"),css=r("src/index.css");
test("V5 preview badge",()=>{assert.match(badge,/wspv5qa3a5e8018/);assert.match(badge,/QA \/ DEV/);assert.match(badge,/NOT PROD/);});
test("OCR retry safety",()=>{assert.match(automation,/edgeFunctionErrorDetails/);assert.match(automation,/invokeOcrWithRetry/);assert.match(automation,/\[429,500,502,503,504\]/);assert.match(automation,/Original invoice is safely stored/);});
test("OCR columns/sticky/suggested product",()=>{assert.match(automation,/>Sr No</);assert.match(automation,/>Size \(ml\)</);assert.match(automation,/OCR_COLUMN_OPTIONS/);assert.match(automation,/Suggested Product Name/);assert.match(css,/ocr-review-table thead th/);assert.match(css,/position:sticky/);});
test("OCR line preview remains non-mutating",()=>{assert.match(automation,/OcrProductImagePreview/);assert.match(preview,/discoverProducts/);assert.doesNotMatch(preview,/applyProductImageChoice|set_product_image/);});
test("Add Product uses pre-save internet image chooser",()=>{assert.match(form,/getPreSaveProductImageChoices/);assert.match(form,/preSaveImageSelection/);assert.match(form,/Try Another Image/);});
test("OCR can edit linked Product and return",()=>{assert.match(automation,/Edit Product/);assert.match(automation,/ocrLineIndex/);assert.match(edit,/useSearchParams/);assert.match(edit,/Save & Return to OCR/);assert.match(edit,/\/purchasing\/ocr/);});
test("MRP safety remains",()=>{assert.match(automation,/linePriceSanity/);assert.match(automation,/priceSanity\.impossible/);assert.match(automation,/PRICE_MRP_AUTO_SUGGESTED/);assert.match(automation,/ocr-pack-auto-warning/);});
