import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { useShop } from "../context/ShopContext";

export default function AutomationHub(){const{products}=useShop();const navigate=useNavigate();const[file,setFile]=useState(null);const[result,setResult]=useState(null);const[matches,setMatches]=useState({});const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
function toBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(",")[1]);r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
async function analyze(){if(!file)return;if(file.size>4*1024*1024){setMessage("F0 OCR accepts files up to 4 MB. Compress or split this invoice first.");return}setBusy(true);setMessage("");try{const contentBase64=await toBase64(file);const{data,error}=await supabase.functions.invoke("ocr-invoice",{body:{contentBase64,contentType:file.type||"application/octet-stream"}});if(error)throw error;if(!data?.ok)throw new Error(data?.message||"OCR failed");setResult(data.invoice);const next={};for(let i=0;i<(data.invoice.items||[]).length;i++){const item=data.invoice.items[i];const{data:m}=await supabase.rpc("match_product_text",{p_text:item.description,p_supplier_id:null,p_limit:5});next[i]=m||[]}setMatches(next)}catch(e){setMessage(e.message||String(e))}finally{setBusy(false)}}
function useDraft(){if(!result)return;const lines=(result.items||[]).map((item,i)=>{const selected=(matches[i]||[])[0];const p=products.find((x)=>x.id===selected?.product_id);return{description:item.description,productId:p?.id||"",quantity:Number(item.quantity||1),caseCount:0,unitsPerCase:p?.unitsPerCase||1,looseBottles:Number(item.quantity||1),purchasePrice:Number(item.unitPrice||p?.purchasePrice||0),confidence:item.confidence,matchScore:selected?.score||0}});sessionStorage.setItem("wineshop_ocr_purchase_draft",JSON.stringify({supplierName:result.supplierName||"",invoiceNumber:result.invoiceNumber||"",invoiceDate:result.invoiceDate||new Date().toISOString().slice(0,10),items:lines,sourceFile:file?.name,createdAt:new Date().toISOString()}));navigate("/purchases")}
return <div><div className="page-heading"><div><h2>OCR & Automation Hub</h2><p>Invoice OCR with mandatory human review before stock receipt.</p></div></div>{message&&<div className="purchase-message error">{message}</div>}<div className="settings-grid"><section className="panel"><h3>Purchase Invoice OCR</h3><input type="file" accept="image/*,.pdf,application/pdf" onChange={(e)=>setFile(e.target.files?.[0]||null)}/><br/><br/><button className="primary-button" disabled={!file||busy} onClick={analyze}>{busy?"Analyzing...":"Analyze Invoice"}</button><p><small>Azure Document Intelligence F0 is configured server-side. F0 is intended for low-cost testing and processes only the first two pages of a document; upload files up to 4 MB. Human review is mandatory before inventory changes.</small></p></section><section className="panel"><h3>Compliance / AI Roadmap</h3><p>State excise/compliance reports are not claimed as implemented because the exact Indian state, licensing format and statutory report specification must be selected first.</p><p>Smart reorder is already rule-based. Future anomaly detection and an owner assistant should read audited business data, never bypass transaction controls.</p></section></div>
{result&&<section className="panel" style={{marginTop:16}}><h3>Human Review</h3><p>Supplier: <strong>{result.supplierName||"-"}</strong> · Invoice: <strong>{result.invoiceNumber||"-"}</strong> · Date: <strong>{result.invoiceDate||"-"}</strong></p><div className="data-table-wrapper"><table className="data-table"><thead><tr><th>OCR Description</th><th>Qty</th><th>Unit Price</th><th>Best Product Match</th><th>Score</th></tr></thead><tbody>{(result.items||[]).map((item,i)=>{const m=(matches[i]||[])[0];return <tr key={i}><td>{item.description}</td><td>{item.quantity}</td><td>{item.unitPrice}</td><td>{m?.product_name||"No confident match"}</td><td>{m?.score||"-"}</td></tr>})}</tbody></table></div><button className="primary-button" onClick={useDraft}>Send Reviewed Draft to Receive Stock</button></section>}</div>}
