import SortableTable from "../components/ui/SortableTable";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { useShop } from "../context/ShopContext";
import PageHeader from "../components/ui/PageHeader";
import StatusBadge from "../components/ui/StatusBadge";
import EmptyState from "../components/ui/EmptyState";

export default function BackupRecovery(){const{createBackup}=useShop();const[tests,setTests]=useState([]);const[msg,setMsg]=useState("");const[form,setForm]=useState({environment:"STAGING",reference:"",result:"PASS",notes:""});async function load(){const{data,error}=await supabase.from("backup_restore_tests").select("*").order("tested_at",{ascending:false}).limit(50);if(error)setMsg("Unable to load restore-test history.");else setTests(data||[])}useEffect(()=>{load()},[]);
function exportSnapshot(){const snapshot=createBackup();const blob=new Blob([JSON.stringify(snapshot,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`wineshoppos-operational-snapshot-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
async function record(e){e.preventDefault();const{error}=await supabase.rpc("record_backup_restore_test",{p_environment:form.environment,p_backup_reference:form.reference,p_result:form.result,p_notes:form.notes||null});setMsg(error?"Unable to record restore test.":"Restore test evidence recorded.");if(!error){setForm({...form,reference:"",notes:""});load()}}
return <div><PageHeader title="Backup & Recovery" subtitle="Operational snapshot export plus documented restore-test evidence."/>{msg?<div className="purchase-message">{msg}</div>:null}<div className="settings-grid"><section className="panel"><h3>Recovery Strategy</h3><ol className="runbook-list"><li>Use Supabase platform/database backups appropriate to the subscribed plan.</li><li>Keep migrations and Edge Functions in Git as infrastructure history.</li><li>Export operational JSON snapshots for human-readable emergency reference.</li><li>Perform restore drills in a separate non-production environment.</li><li>Record PASS/FAIL evidence below.</li></ol><button className="primary-button" onClick={exportSnapshot}>Export Operational Snapshot</button><p className="muted-text">This JSON is not a substitute for a PostgreSQL database backup.</p></section><form className="panel" onSubmit={record}><h3>Record Restore Drill</h3><div className="settings-fields"><label>Environment<select value={form.environment} onChange={(e)=>setForm({...form,environment:e.target.value})}><option>STAGING</option><option>TEST</option><option>DISASTER_RECOVERY</option></select></label><label>Backup Reference<input required value={form.reference} onChange={(e)=>setForm({...form,reference:e.target.value})} placeholder="backup id/date/runbook reference"/></label><label>Result<select value={form.result} onChange={(e)=>setForm({...form,result:e.target.value})}><option>PASS</option><option>FAIL</option></select></label><label>Notes<textarea value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></label></div><br/><button className="primary-button">Record Test</button></form></div><section className="panel" style={{marginTop:16}}><h3>Restore Test History</h3>{tests.length===0?<EmptyState title="No restore drill recorded" message="Production backup readiness is not considered proven until a restore drill succeeds."/>:<div className="data-table-wrapper"><SortableTable className="data-table"><thead><tr><th>When</th><th>Environment</th><th>Backup Reference</th><th>Result</th><th>Notes</th></tr></thead><tbody>{tests.map(t=><tr key={t.id}><td>{new Date(t.test_date||t.created_at).toLocaleString("en-IN")}</td><td>{t.environment}</td><td>{t.backup_reference}</td><td><StatusBadge status={t.result}/></td><td>{t.notes||"-"}</td></tr>)}</tbody></SortableTable></div>}</section></div>}
