import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import PageHeader from "../components/ui/PageHeader";
import EmptyState from "../components/ui/EmptyState";

export default function Compliance(){
  const [form,setForm]=useState({stateCode:"",stateName:"",licenseType:"",licenseNumber:"",validFrom:"",validTo:"",exciseRegistration:"",notes:""});
  const [exists,setExists]=useState(false);const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);
  async function load(){const{data,error}=await supabase.from("compliance_profiles").select("*").maybeSingle();if(error){setMsg("Unable to load compliance configuration.");return}if(data){setExists(true);setForm({stateCode:data.state_code||"",stateName:data.state_name||"",licenseType:data.license_type||"",licenseNumber:data.license_number||"",validFrom:data.license_valid_from||"",validTo:data.license_valid_to||"",exciseRegistration:data.excise_registration_number||"",notes:data.notes||""})}}
  useEffect(()=>{load()},[]);
  async function save(e){e.preventDefault();setBusy(true);const{error}=await supabase.rpc("upsert_compliance_profile",{p_state_code:form.stateCode||null,p_state_name:form.stateName||null,p_license_number:form.licenseNumber||null,p_license_type:form.licenseType||null,p_license_valid_from:form.validFrom||null,p_license_valid_to:form.validTo||null,p_excise_registration_number:form.exciseRegistration||null,p_notes:form.notes||null});setMsg(error?"Unable to save compliance configuration.":"Compliance profile saved. No legal report is enabled until its verified state specification is implemented.");if(!error)setExists(true);setBusy(false)}
  return <div><PageHeader title="Liquor Compliance Foundation" subtitle="Store verified state/license metadata without inventing excise or tax rules."/>{msg?<div className="purchase-message">{msg}</div>:null}<div className="settings-grid"><form className="panel" onSubmit={save}><h3>{exists?"Compliance Profile":"Create Compliance Profile"}</h3><div className="settings-fields"><label>State Code<input value={form.stateCode} onChange={(e)=>setForm({...form,stateCode:e.target.value})} placeholder="MH"/></label><label>State Name<input required value={form.stateName} onChange={(e)=>setForm({...form,stateName:e.target.value})} placeholder="Maharashtra"/></label><label>License Type<input required value={form.licenseType} onChange={(e)=>setForm({...form,licenseType:e.target.value})}/></label><label>License Number<input required value={form.licenseNumber} onChange={(e)=>setForm({...form,licenseNumber:e.target.value})}/></label><label>Valid From<input type="date" value={form.validFrom} onChange={(e)=>setForm({...form,validFrom:e.target.value})}/></label><label>Valid To<input type="date" value={form.validTo} onChange={(e)=>setForm({...form,validTo:e.target.value})}/></label><label>Excise Registration Number<input value={form.exciseRegistration} onChange={(e)=>setForm({...form,exciseRegistration:e.target.value})}/></label><label>Notes<textarea value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></label></div><br/><button className="primary-button" disabled={busy}>{busy?"Saving...":"Save Configuration"}</button></form><section className="panel"><h3>Compliance Safety Rule</h3><p>WineShopPOS does not currently claim any generic report is legally excise-compliant.</p><p>State-specific registers, fields and calculations must be added only from verified requirements supplied for the licensed shop.</p><EmptyState title="No invented legal rules" message="This foundation is intentionally configuration-only until a verified state/report specification is provided."/></section></div></div>
}
