import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import PageHeader from "../components/ui/PageHeader";
import FeatureTierBadge from "../components/ui/FeatureTierBadge";
import EmptyState from "../components/ui/EmptyState";
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
export default function CustomerCredit(){const[balances,setBalances]=useState([]);const[message,setMessage]=useState("");const[customer,setCustomer]=useState({name:"",mobile:"",email:""});const[entry,setEntry]=useState({customerId:"",type:"CHARGE",amount:"",reference:"",description:""});
async function load(){const{data,error}=await supabase.rpc("customer_balances");if(error)setMessage("Unable to load customer balances.");else setBalances(data||[])}useEffect(()=>{load()},[]);
async function addCustomer(e){e.preventDefault();const{data,error}=await supabase.rpc("create_customer",{p_full_name:customer.name,p_mobile:customer.mobile||null,p_email:customer.email||null,p_notes:null});if(error)setMessage("Unable to add customer. Mobile number may already exist.");else{setMessage("Customer created.");setCustomer({name:"",mobile:"",email:""});setEntry({...entry,customerId:data});load()}}
async function postEntry(e){e.preventDefault();const{error}=await supabase.rpc("record_customer_credit",{p_customer_id:entry.customerId,p_entry_type:entry.type,p_amount:Number(entry.amount),p_sale_id:null,p_reference:entry.reference||null,p_description:entry.description||null});setMessage(error?"Unable to record customer credit entry.":"Customer credit ledger updated.");if(!error){setEntry({...entry,amount:"",reference:"",description:""});load()}}
return <div><PageHeader title="Customer & Credit" tier="PLUS" subtitle="Optional customer records and Udhaar ledger without slowing normal barcode billing."/>{message?<div className="purchase-message">{message}</div>:null}<div className="settings-grid"><form className="panel" onSubmit={addCustomer}><h3>New Customer <FeatureTierBadge tier="PLUS"/></h3><div className="settings-fields"><label>Name<input required value={customer.name} onChange={(e)=>setCustomer({...customer,name:e.target.value})}/></label><label>Mobile<input value={customer.mobile} onChange={(e)=>setCustomer({...customer,mobile:e.target.value})}/></label><label>Email<input type="email" value={customer.email} onChange={(e)=>setCustomer({...customer,email:e.target.value})}/></label></div><br/><button className="primary-button">Add Customer</button></form><form className="panel" onSubmit={postEntry}><h3>Credit / Payment Entry</h3><div className="settings-fields"><label>Customer<select required value={entry.customerId} onChange={(e)=>setEntry({...entry,customerId:e.target.value})}><option value="">Select customer</option>{balances.map((c)=><option key={c.customer_id} value={c.customer_id}>{c.full_name} · {money.format(c.outstanding)}</option>)}</select></label><label>Entry Type<select value={entry.type} onChange={(e)=>setEntry({...entry,type:e.target.value})}><option value="CHARGE">Udhaar / Charge</option><option value="PAYMENT">Payment Received</option><option value="ADJUSTMENT_DEBIT">Debit Adjustment</option><option value="ADJUSTMENT_CREDIT">Credit Adjustment</option></select></label><label>Amount<input type="number" min="0.01" step="0.01" required value={entry.amount} onChange={(e)=>setEntry({...entry,amount:e.target.value})}/></label><label>Reference<input value={entry.reference} onChange={(e)=>setEntry({...entry,reference:e.target.value})}/></label><label>Description<input value={entry.description} onChange={(e)=>setEntry({...entry,description:e.target.value})}/></label></div><br/><button className="primary-button">Record Entry</button></form></div><section className="panel" style={{marginTop:16}}><h3>Customer Outstanding</h3>{balances.length===0?<EmptyState title="No customer credit records" message="Customer capture remains optional during normal billing."/>:<div className="data-table-wrapper"><table className="data-table"><thead><tr><th>Customer</th><th>Mobile</th><th>Charges</th><th>Payments</th><th>Outstanding</th></tr></thead><tbody>{balances.map((c)=><tr key={c.customer_id}><td>{c.full_name}</td><td>{c.mobile||"-"}</td><td>{money.format(c.total_charges)}</td><td>{money.format(c.total_payments)}</td><td><strong>{money.format(c.outstanding)}</strong></td></tr>)}</tbody></table></div>}</section></div>}
