import SortableTable from "../components/ui/SortableTable";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import PageHeader from "../components/ui/PageHeader";
import EmptyState from "../components/ui/EmptyState";
import StatusBadge from "../components/ui/StatusBadge";

const money = new Intl.NumberFormat("en-IN", { style:"currency", currency:"INR", maximumFractionDigits:2 });
export default function Expenses() {
  const [categories,setCategories]=useState([]); const [rows,setRows]=useState([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({categoryId:"",date:new Date().toISOString().slice(0,10),amount:"",description:"",method:"CASH",reference:""});
  async function load(){const[c,e]=await Promise.all([supabase.from("expense_categories").select("id,name,active").eq("active",true).order("name"),supabase.from("expenses").select("id,expense_date,amount,description,payment_method,reference_number,status,created_at,expense_categories(name)").order("expense_date",{ascending:false}).limit(300)]);if(c.error||e.error)setMessage("Unable to load expense data.");else{setCategories(c.data||[]);setRows(e.data||[])}}
  useEffect(()=>{load()},[]);
  const monthTotal=useMemo(()=>{const month=new Date().toISOString().slice(0,7);return rows.filter((r)=>r.status==="ACTIVE"&&String(r.expense_date).startsWith(month)).reduce((s,r)=>s+Number(r.amount||0),0)},[rows]);
  async function submit(event){event.preventDefault();setBusy(true);const{error}=await supabase.rpc("record_expense",{p_category_id:form.categoryId,p_expense_date:form.date,p_amount:Number(form.amount),p_description:form.description,p_payment_method:form.method,p_reference:form.reference||null});setMessage(error?"Unable to record expense. Check the fields and retry.":"Expense recorded.");if(!error){setForm({...form,amount:"",description:"",reference:""});await load()}setBusy(false)}
  async function voidRow(id){const reason=window.prompt("Reason for voiding this expense");if(!reason)return;const{error}=await supabase.rpc("void_expense",{p_expense_id:id,p_reason:reason});setMessage(error?"Unable to void expense.":"Expense voided and retained in audit history.");if(!error)load()}
  return <div><PageHeader title="Expense Management" subtitle="Track operating expenses so Owner Center can calculate operating profit."/>{message?<div className="purchase-message">{message}</div>:null}
    <div className="settings-grid"><form className="panel" onSubmit={submit}><h3>Record Expense</h3><div className="settings-fields"><label>Date<input type="date" value={form.date} onChange={(e)=>setForm({...form,date:e.target.value})} required/></label><label>Category<select value={form.categoryId} onChange={(e)=>setForm({...form,categoryId:e.target.value})} required><option value="">Select category</option>{categories.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Amount<input type="number" min="0.01" step="0.01" value={form.amount} onChange={(e)=>setForm({...form,amount:e.target.value})} required/></label><label>Payment Method<select value={form.method} onChange={(e)=>setForm({...form,method:e.target.value})}>{["CASH","UPI","CARD","BANK_TRANSFER","CHEQUE","OTHER"].map((x)=><option key={x}>{x}</option>)}</select></label><label>Description<input value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} required/></label><label>Reference<input value={form.reference} onChange={(e)=>setForm({...form,reference:e.target.value})}/></label></div><br/><button className="primary-button" disabled={busy}>{busy?"Saving...":"Record Expense"}</button></form><section className="panel"><h3>This Month</h3><div className="big-number">{money.format(monthTotal)}</div><p className="muted-text">Active expenses for the current calendar month.</p></section></div>
    <section className="panel" style={{marginTop:16}}><h3>Expense History</h3>{rows.length===0?<EmptyState title="No expenses recorded yet" message="Record rent, salaries, electricity, transport, maintenance or other operating expenses."/>:<div className="data-table-wrapper"><SortableTable className="data-table"><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Method</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{rows.map((r)=><tr key={r.id}><td>{r.expense_date}</td><td>{r.expense_categories?.name||"-"}</td><td>{r.description}</td><td>{r.payment_method}</td><td>{money.format(r.amount)}</td><td><StatusBadge status={r.status}/></td><td>{r.status==="ACTIVE"?<button className="secondary-button" onClick={()=>voidRow(r.id)}>Void</button>:null}</td></tr>)}</tbody></SortableTable></div>}</section>
  </div>;
}
