import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import PageHeader from "../components/ui/PageHeader";
import EmptyState from "../components/ui/EmptyState";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
const missing=(e)=>e&&(e.code==="PGRST202"||e.code==="42883"||/inventory_ageing_report|fifo_receipt_lots|does not exist|could not find the function/i.test(e.message||""));

export default function InventoryAgeing(){
  const[ageing,setAgeing]=useState([]);const[fifo,setFifo]=useState([]);const[loading,setLoading]=useState(true);const[available,setAvailable]=useState(true);const[message,setMessage]=useState("");
  async function load(){setLoading(true);setMessage("");const[a,f]=await Promise.all([supabase.rpc("inventory_ageing_report"),supabase.rpc("fifo_receipt_lots")]);if(missing(a.error)||missing(f.error)){setAvailable(false);setAgeing([]);setFifo([]);}else if(a.error||f.error)setMessage("Unable to load receipt ageing/FIFO data.");else{setAvailable(true);setAgeing(a.data||[]);setFifo(f.data||[]);}setLoading(false);}
  useEffect(()=>{load();},[]);
  const totals=useMemo(()=>{const b={};let value=0,old=0,untracked=0;for(const r of ageing){const v=Number(r.cost_value||0);value+=v;b[r.age_bucket]=(b[r.age_bucket]||0)+v;if(["91-180","180+"].includes(r.age_bucket))old+=v;if(r.age_bucket==="UNTRACKED")untracked+=Number(r.quantity||0);}return{b,value,old,untracked};},[ageing]);
  return <div><PageHeader title="Stock Ageing & FIFO" subtitle="Receipt-based inventory age, money tied up in old stock, and oldest-lot rotation visibility." tier="PRO"/>{message&&<div className="purchase-message">{message}</div>}
  {loading?<section className="panel"><p>Loading stock ageing...</p></section>:!available?<section className="panel"><EmptyState title="V2 inventory-cost migration is not active" message="Apply migration 20260830080000 to enable landed cost, receipt lots, ageing and FIFO."/></section>:<>
  <div className="metric-grid four"><div className="metric-card"><span>Inventory Cost Value</span><strong>{money.format(totals.value)}</strong></div><div className="metric-card"><span>91+ Day Cost</span><strong>{money.format(totals.old)}</strong></div><div className="metric-card"><span>180+ Day Cost</span><strong>{money.format(totals.b["180+"]||0)}</strong></div><div className="metric-card"><span>Untracked Bottles</span><strong>{totals.untracked}</strong></div></div>
  <section className="panel" style={{marginTop:16}}><div className="section-row"><div><h3>True Receipt Ageing</h3><p className="muted-text">Legacy/opening/transfer stock without receipt provenance is shown as UNTRACKED, not assigned a fake age.</p></div><button className="secondary-button" onClick={load}>Refresh</button></div><div className="data-table-wrapper"><table className="data-table sticky"><thead><tr><th>Product</th><th>Supplier</th><th>Lot</th><th>Batch</th><th>Receipt Date</th><th>Age</th><th>Bucket</th><th>Qty</th><th>Landed/Bottle</th><th>Cost Value</th><th>%</th></tr></thead><tbody>{ageing.map((r,i)=><tr key={`${r.product_id}-${r.lot_number}-${i}`}><td>{r.product_name}</td><td>{r.supplier_name||"-"}</td><td>{r.lot_number}</td><td>{r.batch_number||"-"}</td><td>{r.receipt_date||"-"}</td><td>{r.age_days==null?"-":`${r.age_days}d`}</td><td>{r.age_bucket}</td><td>{r.quantity}</td><td>{money.format(r.landed_unit_cost||0)}</td><td>{money.format(r.cost_value||0)}</td><td>{Number(r.inventory_percentage||0).toFixed(2)}%</td></tr>)}</tbody></table></div></section>
  <section className="panel" style={{marginTop:16}}><h3>FIFO Rotation Queue</h3><p className="muted-text">Oldest tracked receipt lots first. POS sale stock deduction remains unchanged.</p>{fifo.length===0?<EmptyState title="No tracked receipt lots" message="New V2 purchase receipts create receipt-level lots."/>:<div className="data-table-wrapper"><table className="data-table sticky"><thead><tr><th>Product</th><th>Lot</th><th>Batch</th><th>Received</th><th>Expiry</th><th>Remaining</th><th>Landed/Bottle</th><th>Supplier</th></tr></thead><tbody>{fifo.map((r,i)=><tr key={`${r.product_id}-${r.lot_number}-${i}`}><td>{r.product_name}</td><td>{r.lot_number}</td><td>{r.batch_number||"-"}</td><td>{r.received_at?new Date(r.received_at).toLocaleDateString():"-"}</td><td>{r.expiry_date||"-"}</td><td>{r.remaining_quantity}</td><td>{money.format(r.landed_unit_cost||0)}</td><td>{r.supplier_name||"-"}</td></tr>)}</tbody></table></div>}</section>
  </>}</div>;
}
