import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { useShop } from "../context/ShopContext";
import PageHeader from "../components/ui/PageHeader";
import StatusBadge from "../components/ui/StatusBadge";
import EmptyState from "../components/ui/EmptyState";
import { DonutChartCard, HorizontalBarChartCard } from "../components/charts/BusinessCharts";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
export default function InventoryIntelligence() {
  const { products, suppliers } = useShop();
  const [health, setHealth] = useState([]); const [explain, setExplain] = useState([]); const [productId, setProductId] = useState(""); const [supplierId, setSupplierId] = useState(""); const [message, setMessage] = useState("");
  async function load(){const {data,error}=await supabase.rpc("inventory_health",{p_history_days:30,p_dead_days:45});if(error)setMessage("Unable to load inventory intelligence.");else setHealth(data||[])}
  useEffect(()=>{load()},[]);
  async function explainProduct(id){setProductId(id);setExplain([]);if(!id)return;const{data,error}=await supabase.rpc("stock_explanation",{p_product_id:id,p_days:365});if(error)setMessage("Unable to explain stock movement.");else setExplain(data||[])}
  async function createPO(row){if(!supplierId)return setMessage("Select a supplier before creating a purchase order.");const product=products.find((p)=>p.id===row.product_id);if(!product)return;const qty=Math.max(product.unitsPerCase||1,Number(row.current_stock<=0?product.unitsPerCase:Math.ceil((Number(row.avg_daily||0)*14-Number(row.current_stock||0))/(product.unitsPerCase||1))*(product.unitsPerCase||1)));const{error}=await supabase.rpc("create_purchase_order",{p_supplier_id:supplierId,p_items:[{product_id:row.product_id,quantity:qty,purchase_price:product.purchasePrice}],p_expected_date:null,p_notes:"Created from Inventory Intelligence"});setMessage(error?"Unable to create purchase order.":`Draft purchase order created for ${qty} bottle(s).`)}
  const selected=useMemo(()=>products.find((p)=>p.id===productId),[products,productId]);
  const counts=useMemo(()=>health.reduce((a,r)=>({...a,[r.classification]:(a[r.classification]||0)+1}),{}),[health]);
  const healthChart=useMemo(()=>Object.entries(counts).map(([label,value])=>({label:label.replaceAll("_"," "),value})),[counts]);
  const riskChart=useMemo(()=>health.filter((r)=>["STOCKOUT_RISK","OUT_OF_STOCK"].includes(r.classification)).sort((a,b)=>Number(a.days_remaining??999)-Number(b.days_remaining??999)).slice(0,7).map((r)=>({label:r.product_name,value:Number(r.current_stock||0)})),[health]);
  return <div><PageHeader title="Inventory Intelligence" subtitle="Explain stock, detect health risks and convert reorder needs into purchase orders." tier="PRO"/>{message?<div className="purchase-message">{message}</div>:null}
    <div className="metric-grid four"><div className="metric-card metric-accent-orange"><span>Stockout Risk</span><strong>{counts.STOCKOUT_RISK||0}</strong></div><div className="metric-card metric-accent-indigo"><span>Dead Stock</span><strong>{counts.DEAD||0}</strong></div><div className="metric-card metric-accent-blue"><span>Overstock</span><strong>{counts.OVERSTOCK||0}</strong></div><div className="metric-card metric-accent-red"><span>Out of Stock</span><strong>{counts.OUT_OF_STOCK||0}</strong></div></div>
    <div className="dashboard-chart-grid" style={{marginTop:16}}><DonutChartCard title="Inventory Health Mix" subtitle="Product count by current health classification" data={healthChart} centerLabel="SKUs"/><HorizontalBarChartCard title="Immediate Stock Risk" subtitle="Current bottles for products closest to stockout" data={riskChart}/></div>
    <section className="panel" style={{marginTop:16}}><div className="section-row"><div><h3>Inventory Health</h3><p className="muted-text">30-day sales velocity with 45-day dead-stock threshold.</p></div><label>Supplier for PO<select value={supplierId} onChange={(e)=>setSupplierId(e.target.value)}><option value="">Select supplier</option>{suppliers.map((s)=><option key={s.id} value={s.id}>{s.supplier_name}</option>)}</select></label></div>{health.length===0?<EmptyState title="No inventory health data" message="Products and sales history are required."/>:<div className="data-table-wrapper"><table className="data-table sticky"><thead><tr><th>Product</th><th>Stock</th><th>30d Sales</th><th>Avg/Day</th><th>Days Left</th><th>Inventory Cost</th><th>Health</th><th></th></tr></thead><tbody>{health.map((r)=><tr key={r.product_id}><td>{r.product_name}</td><td>{r.current_stock}</td><td>{r.units_sold}</td><td>{r.avg_daily}</td><td>{r.days_remaining??"-"}</td><td>{money.format(r.inventory_cost)}</td><td><StatusBadge status={r.classification}/></td><td>{["STOCKOUT_RISK","OUT_OF_STOCK"].includes(r.classification)?<button className="secondary-button" onClick={()=>createPO(r)}>Create PO</button>:null}</td></tr>)}</tbody></table></div>}</section>
    <section className="panel" style={{marginTop:16}}><h3>Explain My Stock</h3><label>Product<select value={productId} onChange={(e)=>explainProduct(e.target.value)}><option value="">Select product</option>{products.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{selected?<><h4 style={{marginTop:14}}>{selected.name}</h4><div className="movement-breakdown">{explain.map((r)=><div className="movement-chip" key={r.movement_type}><span>{r.movement_type.replaceAll("_"," ")}</span><strong>{Number(r.quantity_change)>0?"+":""}{r.quantity_change}</strong><small>{r.event_count} event(s)</small></div>)}</div></>:null}</section>
  </div>;
}
