import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { useSaaS } from "../context/SaaSContext";

export default function PlatformAdmin(){
 const saas=useSaaS();const[accounts,setAccounts]=useState([]);const[msg,setMsg]=useState("");
 const[account,setAccount]=useState({email:"",plan:"BASIC",status:"ACTIVE",expiresAt:"",demo:false,trialDays:2});
 const[runtime,setRuntime]=useState({latest:saas.latestVersion||"V4",minimum:saas.minimumSupportedVersion||"V4",force:false,updateMessage:saas.updateMessage||""});
 const[notice,setNotice]=useState({message:"",severity:"INFO",hours:24});
 async function load(){const{data,error}=await supabase.rpc("saas_admin_list_accounts");if(error)setMsg(error.message);else setAccounts(data||[])}
 useEffect(()=>{void load()},[]);
 async function saveAccount(e){e.preventDefault();const{error}=await supabase.rpc("saas_admin_set_account_by_email",{p_email:account.email.trim(),p_plan_code:account.plan,p_status:account.status,p_expires_at:account.expiresAt?new Date(account.expiresAt).toISOString():null,p_demo:account.demo,p_trial_days:Number(account.trialDays||2)});if(error)setMsg(error.message);else{setMsg(account.demo?"Demo configured. Trial starts on first demo login.":"Subscription updated.");await load()}}
 async function saveRuntime(e){e.preventDefault();const{error}=await supabase.rpc("saas_admin_set_runtime",{p_latest_version:runtime.latest,p_minimum_supported_version:runtime.minimum,p_force_update:runtime.force,p_update_message:runtime.updateMessage});if(error)setMsg(error.message);else{setMsg("Version controls saved.");await saas.refresh()}}
 async function publish(e){e.preventDefault();const{error}=await supabase.rpc("saas_admin_publish_announcement",{p_message:notice.message,p_severity:notice.severity,p_hours:Number(notice.hours||24)});if(error)setMsg(error.message);else{setMsg("Flash message published.");setNotice({...notice,message:""});await saas.refresh()}}
 return <div style={{padding:24,maxWidth:1200,margin:"0 auto"}}><h1>WineShopPOS Platform Control</h1><p>Provider-only subscriptions, trials, version notices and flash messages.</p>{msg?<div className="purchase-message">{msg}</div>:null}
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:16}}>
 <form className="auth-card" onSubmit={saveAccount}><h2>Account / Subscription</h2><label>Email<input type="email" required value={account.email} onChange={e=>setAccount({...account,email:e.target.value})}/></label><label><input type="checkbox" checked={account.demo} onChange={e=>setAccount({...account,demo:e.target.checked})}/> Disposable demo account</label>{account.demo?<label>Trial days<input type="number" min="1" max="30" value={account.trialDays} onChange={e=>setAccount({...account,trialDays:e.target.value})}/></label>:<><label>Plan<select value={account.plan} onChange={e=>setAccount({...account,plan:e.target.value})}><option>BASIC</option><option>PLUS</option><option>PRO</option><option>ENTERPRISE</option></select></label><label>Status<select value={account.status} onChange={e=>setAccount({...account,status:e.target.value})}><option>ACTIVE</option><option>TRIALING</option><option>PAST_DUE</option><option>SUSPENDED</option><option>EXPIRED</option><option>CANCELLED</option></select></label><label>Expires<input type="datetime-local" value={account.expiresAt} onChange={e=>setAccount({...account,expiresAt:e.target.value})}/></label></>}<button className="primary-button">Save Account</button></form>
 <form className="auth-card" onSubmit={saveRuntime}><h2>Version Control</h2><label>Latest version<input value={runtime.latest} onChange={e=>setRuntime({...runtime,latest:e.target.value})}/></label><label>Minimum supported<input value={runtime.minimum} onChange={e=>setRuntime({...runtime,minimum:e.target.value})}/></label><label><input type="checkbox" checked={runtime.force} onChange={e=>setRuntime({...runtime,force:e.target.checked})}/> Force update notice</label><label>Update message<textarea rows="3" value={runtime.updateMessage} onChange={e=>setRuntime({...runtime,updateMessage:e.target.value})}/></label><button className="primary-button">Save Version Controls</button></form>
 <form className="auth-card" onSubmit={publish}><h2>Flash Message</h2><label>Message<textarea required rows="4" value={notice.message} onChange={e=>setNotice({...notice,message:e.target.value})}/></label><label>Severity<select value={notice.severity} onChange={e=>setNotice({...notice,severity:e.target.value})}><option>INFO</option><option>SUCCESS</option><option>WARNING</option><option>CRITICAL</option></select></label><label>Show hours<input type="number" min="1" max="720" value={notice.hours} onChange={e=>setNotice({...notice,hours:e.target.value})}/></label><button className="primary-button">Publish Flash Message</button></form>
 </div><h2 style={{marginTop:24}}>Accounts</h2><div style={{overflowX:"auto"}}><table style={{width:"100%"}}><thead><tr><th>Email</th><th>Role</th><th>Mode</th><th>Plan</th><th>Status</th><th>Expiry</th></tr></thead><tbody>{accounts.map(a=><tr key={`${a.user_id}-${a.email}`}><td>{a.email}</td><td>{a.role}</td><td>{a.demo?"DEMO":"LIVE"}</td><td>{a.plan_code}</td><td>{a.status}</td><td>{a.expires_at?new Date(a.expires_at).toLocaleString():"No expiry"}</td></tr>)}</tbody></table></div></div>
}
