import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useShop } from "../context/ShopContext";
import { useScanner } from "../context/ScannerContext";
import { supabase } from "../lib/supabase";
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
export default function POS(){const{products,getStock,completeSale}=useShop();const{lastScan,successBeep,errorBeep}=useScanner();const navigate=useNavigate();const[search,setSearch]=useState("");const[cart,setCart]=useState([]);const[paymentMethod,setPaymentMethod]=useState("CASH");const[paymentReference,setPaymentReference]=useState("");const[discount,setDiscount]=useState(0);const[message,setMessage]=useState("Scanner ready");const[unknown,setUnknown]=useState("");const[busy,setBusy]=useState(false);const[customers,setCustomers]=useState([]);const[customerId,setCustomerId]=useState("");
const active=products.filter(p=>p.active);const results=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return[];return active.filter(p=>[p.name,p.brand,p.sku,p.barcode].some(v=>String(v).toLowerCase().includes(q))).slice(0,8)},[search,active]);
useEffect(()=>{if(navigator.onLine)supabase.from("customers").select("id,full_name,mobile").eq("active",true).order("full_name").limit(200).then(({data})=>setCustomers(data||[]))},[]);
function qty(id){return cart.find(i=>i.product.id===id)?.quantity||0}function add(p){const stock=getStock(p.id);if(qty(p.id)>=stock){errorBeep();setMessage(`Only ${stock} unit(s) available for ${p.name}.`);return false}setCart(c=>{const x=c.find(i=>i.product.id===p.id);return x?c.map(i=>i.product.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{product:p,quantity:1}]});setUnknown("");setMessage(`${p.name} added.`);successBeep();return true}
function processBarcode(code){const p=active.find(x=>x.barcode===code);if(!p){errorBeep();setUnknown(code);setMessage(`PRODUCT NOT FOUND: ${code}`);return}add(p)}
useEffect(()=>{if(lastScan?.barcode)processBarcode(lastScan.barcode)},[lastScan?.id]);
function change(id,d){const i=cart.find(x=>x.product.id===id);if(!i)return;const next=i.quantity+d;if(next<=0)return setCart(c=>c.filter(x=>x.product.id!==id));if(next>getStock(id)){errorBeep();return setMessage(`Only ${getStock(id)} unit(s) available.`)}setCart(c=>c.map(x=>x.product.id===id?{...x,quantity:next}:x))}
const subtotal=cart.reduce((s,i)=>s+i.product.price*i.quantity,0);const disc=Math.max(0,Number(discount||0));const total=Math.max(0,subtotal-disc);
async function checkout(){setBusy(true);const r=await completeSale(cart,paymentMethod,{discount:disc,paymentReference});if(!r.ok){setBusy(false);errorBeep();setMessage(r.message);return}if(!r.offline&&customerId){const{error}=await supabase.rpc("link_sale_customer",{p_sale_id:r.sale.id,p_customer_id:customerId});if(error)setMessage("Sale completed, but customer could not be attached. The sale itself is safe.")}
setBusy(false);successBeep();setCart([]);setDiscount(0);setPaymentReference("");setCustomerId("");if(r.offline){setMessage(r.message);return}navigate(`/sales/${r.sale.id}`)}
return <div><div className="page-heading"><div><h2>Fast POS Billing</h2><p>Global HID scanner active — scan, collect payment and print.</p></div><button className="secondary-button" onClick={()=>navigate("/pos/scanner")}>Scanner Test</button></div>{unknown&&<div className="product-not-found"><strong>PRODUCT NOT FOUND</strong><span>{unknown}</span><button className="primary-button" onClick={()=>navigate(`/products/new?barcode=${encodeURIComponent(unknown)}`)}>Add Product with this Barcode</button></div>}
<div className="pos-layout"><div className="pos-left"><div className="panel"><label>Manual Search<input style={{width:"100%"}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, barcode, SKU, brand..."/></label>{results.map(p=><button key={p.id} className="search-result" onClick={()=>add(p)}><span>{p.name}</span><span>{money.format(p.price)} · Stock {getStock(p.id)}</span></button>)}<div className="purchase-message" style={{marginTop:10}}>{message}</div></div><div className="panel scanner-commercial-card" style={{marginTop:14}}><strong>Scanner Ready</strong><p>Rapid keystrokes + Enter are captured globally. Scanner text is restored out of discount/payment fields.</p><p>Test barcode: <code>8900000010016</code></p></div></div>
<div className="panel"><h3>Cart</h3><div className="data-table-wrapper"><table className="data-table"><thead><tr><th>Product</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>{cart.map(i=><tr key={i.product.id}><td>{i.product.name}</td><td><button onClick={()=>change(i.product.id,-1)}>-</button> {i.quantity} <button onClick={()=>change(i.product.id,1)}>+</button></td><td>{money.format(i.product.price)}</td><td>{money.format(i.product.price*i.quantity)}</td></tr>)}</tbody></table></div><hr/><label>Customer (optional)<select value={customerId} onChange={e=>setCustomerId(e.target.value)} disabled={!navigator.onLine}><option value="">Walk-in customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.full_name}{c.mobile?` · ${c.mobile}`:""}</option>)}</select></label><p>Subtotal <strong>{money.format(subtotal)}</strong></p><label>Discount<input type="number" min="0" max={subtotal} value={discount} onChange={e=>setDiscount(e.target.value)}/></label><h2>Total {money.format(total)}</h2><div className="payment-methods">{["CASH","UPI","CARD"].map(m=><button type="button" key={m} className={paymentMethod===m?"payment-button active":"payment-button"} onClick={()=>setPaymentMethod(m)}>{m}</button>)}</div>{paymentMethod!=="CASH"&&<label>Payment Reference<input value={paymentReference} onChange={e=>setPaymentReference(e.target.value)}/></label>}<br/><button className="primary-button" disabled={!cart.length||busy} onClick={checkout}>{busy?"Processing...":navigator.onLine?"Complete Sale":"Save Offline Sale"}</button><p className="muted-text">Customer capture is optional. Udhaar/credit entries are managed under Operations → Customer & Credit so the normal cashier flow remains fast.</p></div></div></div>}
