import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { useAuth } from "../context/AuthContext";

export default function PrinterSettings(){const{profile}=useAuth();const[form,setForm]=useState({store_address:"",store_phone:"",tax_registration_number:"",receipt_footer:"THANK YOU",printer_paper_mm:80});const[message,setMessage]=useState("");
useEffect(()=>{supabase.from("shop_settings").select("store_address,store_phone,tax_registration_number,receipt_footer,printer_paper_mm").maybeSingle().then(({data,error})=>{if(error)setMessage(error.message);else if(data)setForm({...form,...data})})},[]);
async function save(e){e.preventDefault();const{error}=await supabase.from("shop_settings").update(form).eq("shop_id",profile.shop_id);setMessage(error?error.message:"Receipt settings saved.")}
function testPrint(){window.print()}
return <div><div className="page-heading"><div><h2>Thermal Printer</h2><p>80mm/58mm browser-print receipt optimized for installed USB/Bluetooth printers.</p></div></div>{message&&<div className="purchase-message">{message}</div>}
<div className="settings-grid"><form className="panel" onSubmit={save}><h3>Receipt Header</h3><div className="settings-fields"><label>Store Address<textarea value={form.store_address||""} onChange={(e)=>setForm({...form,store_address:e.target.value})}/></label><label>Phone<input value={form.store_phone||""} onChange={(e)=>setForm({...form,store_phone:e.target.value})}/></label><label>Registration / GST / License text<input value={form.tax_registration_number||""} onChange={(e)=>setForm({...form,tax_registration_number:e.target.value})}/></label><label>Paper Width<select value={form.printer_paper_mm} onChange={(e)=>setForm({...form,printer_paper_mm:Number(e.target.value)})}><option value={80}>80 mm</option><option value={58}>58 mm</option></select></label><label>Receipt Footer<input value={form.receipt_footer||""} onChange={(e)=>setForm({...form,receipt_footer:e.target.value})}/></label></div><br/><button className="primary-button">Save</button></form>
<section className="panel print-test-ticket"><h3>Printer Test</h3><p><strong>{profile?.shop_name}</strong></p><p>{form.store_address}</p><div className="receipt-rule"/><p>Printer test line</p><p>2 × ₹180 = ₹360</p><div className="receipt-rule"/><h3>TOTAL ₹360</h3><p>{form.receipt_footer}</p><button className="primary-button no-print" onClick={testPrint}>Open Print Dialog</button><p className="no-print"><small>Choose your installed thermal printer and set margins to None/Minimum. Static web apps cannot safely force silent raw ESC/POS printing across arbitrary printer models.</small></p></section></div></div>}
