import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { useShop } from "../context/ShopContext";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
const line=()=>({productId:"",quantity:12,purchasePrice:0});
export default function Procurement(){const{products,suppliers,refreshAll}=useShop();const[orders,setOrders]=useState([]);const[balances,setBalances]=useState([]);const[payment,setPayment]=useState({supplierId:"",amount:"",method:"BANK_TRANSFER",reference:""});const[supplierId,setSupplierId]=useState("");const[items,setItems]=useState([line()]);const[expected,setExpected]=useState("");const[message,setMessage]=useState("");
async function load(){const[po,b]=await Promise.all([supabase.from("purchase_orders").select(`*,purchase_order_items(*)`).order("created_at",{ascending:false}).limit(100),supabase.rpc("supplier_balances")]);if(po.error)setMessage(po.error.message);else setOrders(po.data||[]);if(b.error)setMessage(b.error.message);else setBalances(b.data||[])}useEffect(()=>{load()},[]);
function update(i,k,v){setItems((x)=>x.map((r,n)=>n===i?{...r,[k]:v,...(k==="productId"?{purchasePrice:products.find((p)=>p.id===v)?.purchasePrice||0}:{})}:r))}
const total=useMemo(()=>items.reduce((s,i)=>s+Number(i.quantity||0)*Number(i.purchasePrice||0),0),[items]);
async function createPO(e){e.preventDefault();const payload=items.filter((i)=>i.productId&&Number(i.quantity)>0).map((i)=>({product_id:i.productId,quantity:Number(i.quantity),purchase_price:Number(i.purchasePrice)}));const{error}=await supabase.rpc("create_purchase_order",{p_supplier_id:supplierId,p_items:payload,p_expected_date:expected||null,p_notes:null});setMessage(error?error.message:"Purchase order created.");if(!error){setItems([line()]);load()}}
async function setStatus(id,status){const{error}=await supabase.rpc("set_purchase_order_status",{p_po_id:id,p_status:status});setMessage(error?error.message:`PO ${status.toLowerCase()}.`);if(!error)load()}
async function receive(po){const inv=prompt("Supplier invoice number");if(!inv)return;const{error}=await supabase.rpc("receive_purchase_order",{p_po_id:po.id,p_invoice_number:inv,p_invoice_date:new Date().toISOString().slice(0,10),p_receive_items:null,p_notes:"Received from PO screen"});setMessage(error?error.message:"PO goods received and inventory updated.");if(!error){await Promise.all([load(),refreshAll()])}}
async function pay(e){e.preventDefault();const{error}=await supabase.rpc("record_supplier_payment",{p_supplier_id:payment.supplierId,p_amount:Number(payment.amount),p_payment_method:payment.method,p_reference:payment.reference||null,p_payment_date:new Date().toISOString().slice(0,10),p_notes:null});setMessage(error?error.message:"Supplier payment recorded.");if(!error){setPayment({...payment,amount:"",reference:""});load()}}
async function purchaseReturn(){const productId=prompt("Paste/select product UUID to return (use Products screen if needed)");if(!productId)return;const qty=Number(prompt("Quantity to return",1));const p=products.find((x)=>x.id===productId);if(!p)return setMessage("Product UUID not found in this shop.");const sid=prompt("Supplier UUID",supplierId||suppliers[0]?.id||"");if(!sid)return;const reason=prompt("Reason","Damaged/incorrect supply");if(!reason)return;const{error}=await supabase.rpc("create_purchase_return",{p_supplier_id:sid,p_items:[{product_id:productId,quantity:qty,purchase_price:p.purchasePrice}],p_reason:reason,p_purchase_id:null});setMessage(error?error.message:"Purchase return completed and stock reduced.");if(!error){await Promise.all([load(),refreshAll()])}}
return <div><div className="page-heading"><div><h2>Supplier & Purchasing</h2><p>PO → receive → supplier balance → payment → purchase return.</p></div><button className="secondary-button" onClick={purchaseReturn}>Supplier Return</button></div>{message&&<div className="purchase-message">{message}</div>}
<div className="settings-grid"><form className="panel" onSubmit={createPO}><h3>Create Purchase Order</h3><label>Supplier<select value={supplierId} onChange={(e)=>setSupplierId(e.target.value)} required><option value="">Select supplier</option>{suppliers.map((s)=><option key={s.id} value={s.id}>{s.supplier_name}</option>)}</select></label><label>Expected Date<input type="date" value={expected} onChange={(e)=>setExpected(e.target.value)}/></label><div className="data-table-wrapper"><table className="data-table"><thead><tr><th>Product</th><th>Qty</th><th>Purchase Price</th><th></th></tr></thead><tbody>{items.map((i,n)=><tr key={n}><td><select value={i.productId} onChange={(e)=>update(n,"productId",e.target.value)} required><option value="">Select</option>{products.filter((p)=>p.active).map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></td><td><input type="number" min="1" value={i.quantity} onChange={(e)=>update(n,"quantity",e.target.value)}/></td><td><input type="number" min="0" step="0.01" value={i.purchasePrice} onChange={(e)=>update(n,"purchasePrice",e.target.value)}/></td><td><button type="button" onClick={()=>setItems((x)=>x.filter((_,xidx)=>xidx!==n))}>×</button></td></tr>)}</tbody></table></div><p><strong>Total: {money.format(total)}</strong></p><div className="button-row"><button type="button" className="secondary-button" onClick={()=>setItems((x)=>[...x,line()])}>Add Line</button><button className="primary-button">Create PO</button></div></form>
<form className="panel" onSubmit={pay}><h3>Record Supplier Payment</h3><div className="settings-fields"><label>Supplier<select value={payment.supplierId} onChange={(e)=>setPayment({...payment,supplierId:e.target.value})} required><option value="">Select</option>{suppliers.map((s)=><option key={s.id} value={s.id}>{s.supplier_name}</option>)}</select></label><label>Amount<input type="number" min="0.01" step="0.01" value={payment.amount} onChange={(e)=>setPayment({...payment,amount:e.target.value})} required/></label><label>Method<select value={payment.method} onChange={(e)=>setPayment({...payment,method:e.target.value})}><option>BANK_TRANSFER</option><option>UPI</option><option>CASH</option><option>CARD</option><option>CHEQUE</option><option>OTHER</option></select></label><label>Reference<input value={payment.reference} onChange={(e)=>setPayment({...payment,reference:e.target.value})}/></label></div><br/><button className="primary-button">Record Payment</button></form></div>
<section className="panel" style={{marginTop:16}}><h3>Supplier Balance</h3><div className="data-table-wrapper"><table className="data-table"><thead><tr><th>Supplier</th><th>Purchases</th><th>Payments</th><th>Returns</th><th>Balance</th></tr></thead><tbody>{balances.map((b)=><tr key={b.supplier_id}><td>{b.supplier_name}</td><td>{money.format(b.purchases)}</td><td>{money.format(b.payments)}</td><td>{money.format(b.returns)}</td><td><strong>{money.format(b.balance)}</strong></td></tr>)}</tbody></table></div></section>
<section className="panel" style={{marginTop:16}}><h3>Purchase Orders</h3><div className="data-table-wrapper"><table className="data-table"><thead><tr><th>PO</th><th>Supplier</th><th>Status</th><th>Expected</th><th>Total</th><th>Action</th></tr></thead><tbody>{orders.map((o)=><tr key={o.id}><td>{o.po_number}</td><td>{suppliers.find((s)=>s.id===o.supplier_id)?.supplier_name||o.supplier_id.slice(0,8)}</td><td>{o.status}</td><td>{o.expected_date||"-"}</td><td>{money.format(o.subtotal)}</td><td>{o.status==="DRAFT"&&<button className="secondary-button" onClick={()=>setStatus(o.id,"SENT")}>Mark Sent</button>} {["DRAFT","SENT","PARTIALLY_RECEIVED"].includes(o.status)&&<button className="primary-button" onClick={()=>receive(o)}>Receive</button>}</td></tr>)}</tbody></table></div></section></div>}
