import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { useShop } from "../context/ShopContext";
import FeatureTierBadge from "../components/ui/FeatureTierBadge";
import PageHeader from "../components/ui/PageHeader";
import StatusBadge from "../components/ui/StatusBadge";
import EmptyState from "../components/ui/EmptyState";
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
const line=()=>({productId:"",quantity:12,purchasePrice:0});
export default function Procurement(){const{products,suppliers,refreshAll}=useShop();const[orders,setOrders]=useState([]);const[balances,setBalances]=useState([]);const[supplierId,setSupplierId]=useState("");const[items,setItems]=useState([line()]);const[expected,setExpected]=useState("");const[message,setMessage]=useState("");const[payment,setPayment]=useState({supplierId:"",amount:"",method:"BANK_TRANSFER",reference:""});const[receive,setReceive]=useState({poId:"",invoice:"",date:new Date().toISOString().slice(0,10)});const[ret,setRet]=useState({supplierId:"",productId:"",qty:1,reason:"Damaged/incorrect supply"});
async function load(){const[po,b]=await Promise.all([supabase.from("purchase_orders").select("*,purchase_order_items(*)").order("created_at",{ascending:false}).limit(150),supabase.rpc("supplier_balances")]);if(po.error||b.error)setMessage("Unable to load procurement data.");else{setOrders(po.data||[]);setBalances(b.data||[])}}useEffect(()=>{load()},[]);
function update(i,k,v){setItems(x=>x.map((r,n)=>n===i?{...r,[k]:v,...(k==="productId"?{purchasePrice:products.find(p=>p.id===v)?.purchasePrice||0}:{})}:r))}const total=useMemo(()=>items.reduce((s,i)=>s+Number(i.quantity||0)*Number(i.purchasePrice||0),0),[items]);
async function createPO(e){e.preventDefault();const payload=items.filter(i=>i.productId&&Number(i.quantity)>0).map(i=>({product_id:i.productId,quantity:Number(i.quantity),purchase_price:Number(i.purchasePrice)}));const{error}=await supabase.rpc("create_purchase_order",{p_supplier_id:supplierId,p_items:payload,p_expected_date:expected||null,p_notes:null});setMessage(error?"Unable to create purchase order.":"Draft purchase order created.");if(!error){setItems([line()]);await load()}}
async function rpc(fn,args,ok){const{error}=await supabase.rpc(fn,args);setMessage(error?`Unable to complete ${ok.toLowerCase()}.`:ok);if(!error){await Promise.all([load(),refreshAll()])}}
async function receivePO(e){e.preventDefault();if(!receive.poId)return;const{error}=await supabase.rpc("receive_purchase_order",{p_po_id:receive.poId,p_invoice_number:receive.invoice,p_invoice_date:receive.date,p_receive_items:null,p_notes:"Received from consolidated Procurement"});setMessage(error?"Unable to receive this purchase order. Check status, invoice number and quantities.":"Goods received; inventory and supplier balance updated transactionally.");if(!error){setReceive({...receive,poId:"",invoice:""});await Promise.all([load(),refreshAll()])}}
async function pay(e){e.preventDefault();const{error}=await supabase.rpc("record_supplier_payment",{p_supplier_id:payment.supplierId,p_amount:Number(payment.amount),p_payment_method:payment.method,p_reference:payment.reference||null,p_payment_date:new Date().toISOString().slice(0,10),p_notes:null});setMessage(error?"Unable to record supplier payment.":"Supplier payment recorded.");if(!error){setPayment({...payment,amount:"",reference:""});load()}}
async function purchaseReturn(e){e.preventDefault();const p=products.find(x=>x.id===ret.productId);if(!p)return;const{error}=await supabase.rpc("create_purchase_return",{p_supplier_id:ret.supplierId,p_items:[{product_id:ret.productId,quantity:Number(ret.qty),purchase_price:p.purchasePrice}],p_reason:ret.reason,p_purchase_id:null});setMessage(error?"Unable to complete supplier return.":"Supplier return completed; stock reduced with movement history.");if(!error){setRet({...ret,productId:"",qty:1});await Promise.all([load(),refreshAll()])}}
return <div><PageHeader title="Advanced Supplier & Procurement" subtitle="Draft → approval → send → receive → supplier balance/payment → purchase return." tier="PLUS"/>{message?<div className="purchase-message">{message}</div>:null}
<div className="settings-grid"><form className="panel" onSubmit={createPO}><h3>Create Purchase Order <FeatureTierBadge tier="PLUS"/></h3><div className="settings-fields"><label>Supplier<select value={supplierId} onChange={e=>setSupplierId(e.target.value)} required><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.supplier_name}</option>)}</select></label><label>Expected Date<input type="date" value={expected} onChange={e=>setExpected(e.target.value)}/></label></div><div className="data-table-wrapper"><table className="data-table"><thead><tr><th>Product</th><th>Qty</th><th>Purchase Price</th><th></th></tr></thead><tbody>{items.map((i,n)=><tr key={n}><td><select value={i.productId} onChange={e=>update(n,"productId",e.target.value)} required><option value="">Select</option>{products.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></td><td><input type="number" min="1" value={i.quantity} onChange={e=>update(n,"quantity",e.target.value)}/></td><td><input type="number" min="0" step="0.01" value={i.purchasePrice} onChange={e=>update(n,"purchasePrice",e.target.value)}/></td><td><button type="button" className="icon-button" onClick={()=>setItems(x=>x.filter((_,xidx)=>xidx!==n))}>×</button></td></tr>)}</tbody></table></div><p><strong>Total: {money.format(total)}</strong></p><div className="button-row"><button type="button" className="secondary-button" onClick={()=>setItems(x=>[...x,line()])}>Add Line</button><button className="primary-button">Create Draft PO</button></div></form>
<form className="panel" onSubmit={receivePO}><h3>Receive Approved/Sent PO</h3><div className="settings-fields"><label>Purchase Order<select value={receive.poId} onChange={e=>setReceive({...receive,poId:e.target.value})} required><option value="">Select ready PO</option>{orders.filter(o=>["APPROVED","SENT","PARTIALLY_RECEIVED"].includes(o.status)).map(o=><option key={o.id} value={o.id}>{o.po_number} · {o.status}</option>)}</select></label><label>Supplier Invoice<input required value={receive.invoice} onChange={e=>setReceive({...receive,invoice:e.target.value})}/></label><label>Invoice Date<input type="date" required value={receive.date} onChange={e=>setReceive({...receive,date:e.target.value})}/></label></div><p className="muted-text">Inventory changes only inside the controlled receive RPC.</p><button className="primary-button">Receive Goods</button></form></div>
<div className="settings-grid" style={{marginTop:16}}><form className="panel" onSubmit={pay}><h3>Supplier Payment</h3><div className="settings-fields"><label>Supplier<select value={payment.supplierId} onChange={e=>setPayment({...payment,supplierId:e.target.value})} required><option value="">Select</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.supplier_name}</option>)}</select></label><label>Amount<input type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} required/></label><label>Method<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}>{["BANK_TRANSFER","UPI","CASH","CARD","CHEQUE","OTHER"].map(m=><option key={m}>{m}</option>)}</select></label><label>Reference<input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label></div><button className="primary-button">Record Payment</button></form>
<form className="panel" onSubmit={purchaseReturn}><h3>Purchase Return</h3><div className="settings-fields"><label>Supplier<select required value={ret.supplierId} onChange={e=>setRet({...ret,supplierId:e.target.value})}><option value="">Select</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.supplier_name}</option>)}</select></label><label>Product<select required value={ret.productId} onChange={e=>setRet({...ret,productId:e.target.value})}><option value="">Select</option>{products.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Quantity<input type="number" min="1" required value={ret.qty} onChange={e=>setRet({...ret,qty:e.target.value})}/></label><label>Reason<input required value={ret.reason} onChange={e=>setRet({...ret,reason:e.target.value})}/></label></div><button className="secondary-button">Complete Return</button></form></div>
<section className="panel" style={{marginTop:16}}><h3>Purchase Orders</h3>{orders.length===0?<EmptyState title="No purchase orders" message="Create a draft purchase order to begin procurement."/>:<div className="data-table-wrapper"><table className="data-table sticky"><thead><tr><th>PO</th><th>Supplier</th><th>Status</th><th>Expected</th><th>Total</th><th>Next Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.po_number}</td><td>{suppliers.find(s=>s.id===o.supplier_id)?.supplier_name||"Supplier"}</td><td><StatusBadge status={o.status}/></td><td>{o.expected_date||"-"}</td><td>{money.format(o.subtotal)}</td><td><div className="button-row compact">{o.status==="DRAFT"?<button className="secondary-button" onClick={()=>rpc("submit_purchase_order",{p_po_id:o.id},"Submitted for approval")}>Submit</button>:null}{o.status==="APPROVAL_PENDING"?<button className="primary-button" onClick={()=>rpc("approve_purchase_order",{p_po_id:o.id},"Purchase order approved")}>Approve</button>:null}{o.status==="APPROVED"?<button className="secondary-button" onClick={()=>rpc("set_purchase_order_status",{p_po_id:o.id,p_status:"SENT"},"Purchase order marked sent")}>Mark Sent</button>:null}</div></td></tr>)}</tbody></table></div>}</section>
<section className="panel" style={{marginTop:16}}><h3>Supplier Balance</h3><div className="data-table-wrapper"><table className="data-table"><thead><tr><th>Supplier</th><th>Purchases</th><th>Payments</th><th>Returns</th><th>Balance</th></tr></thead><tbody>{balances.map(b=><tr key={b.supplier_id}><td>{b.supplier_name}</td><td>{money.format(b.purchases)}</td><td>{money.format(b.payments)}</td><td>{money.format(b.returns)}</td><td><strong>{money.format(b.balance)}</strong></td></tr>)}</tbody></table></div></section>
</div>}
