import SortableTable from "../components/ui/SortableTable";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { useAuth } from "../context/AuthContext";
import { offlineQueueCounts } from "../lib/offlineQueue";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
export default function Shifts(){
  const{profile}=useAuth();const[shifts,setShifts]=useState([]);const[opening,setOpening]=useState(0);const[actual,setActual]=useState("");const[corrections,setCorrections]=useState({});const[message,setMessage]=useState("");const[offlineCounts,setOfflineCounts]=useState({total:0,pending:0,conflict:0});const manager=["ADMIN","MANAGER"].includes(profile?.role);
  async function load(){const[{data,error},counts]=await Promise.all([supabase.from("cashier_shifts").select("*").order("opened_at",{ascending:false}).limit(100),offlineQueueCounts().catch(()=>({total:0,pending:0,conflict:0}))]);setOfflineCounts(counts);if(error)setMessage(error.message);else setShifts(data||[]);}
  useEffect(()=>{load();const fn=()=>load();window.addEventListener("online",fn);return()=>window.removeEventListener("online",fn);},[]);
  const mine=shifts.find((s)=>s.cashier_id===profile?.user_id&&["OPEN","CLOSE_REQUESTED"].includes(s.status));
  async function open(){const{error}=await supabase.rpc("open_shift",{p_opening_cash:Number(opening||0),p_notes:null});setMessage(error?error.message:"Shift opened.");if(!error)load();}
  async function requestClose(){if(!navigator.onLine)return setMessage("Internet is required to request shift close.");if(offlineCounts.pending||offlineCounts.conflict)return setMessage(`Sync/resolve offline sales before closing shift. Pending ${offlineCounts.pending}, conflicts ${offlineCounts.conflict}.`);if(actual===""||!Number.isFinite(Number(actual))||Number(actual)<0)return setMessage("Count the physical cash in the drawer and enter Actual Cash before requesting close.");const{error}=await supabase.rpc("request_close_shift",{p_actual_cash:Number(actual),p_notes:"Actual cash physically counted before close request."});setMessage(error?error.message:"Close request sent to manager.");if(!error){setActual("");load();}}
  async function reviseActual(s){const raw=corrections[s.id]??String(s.actual_cash??"");if(raw===""||!Number.isFinite(Number(raw))||Number(raw)<0)return setMessage("Enter a valid physically counted Actual Cash amount.");const{error}=await supabase.rpc("revise_shift_actual_cash",{p_shift_id:s.id,p_actual_cash:Number(raw),p_notes:"Actual cash corrected from Shift screen before approval."});setMessage(error?error.message:"Actual cash corrected and variance recalculated.");if(!error){setCorrections((c)=>{const n={...c};delete n[s.id];return n;});load();}}
  async function approve(s){const difference=Number(s.cash_difference||0);if(Math.abs(difference)>0.009&&!window.confirm(`Cash variance is ${money.format(difference)}. Approve and close this shift with this variance?`))return;const{error}=await supabase.rpc("approve_shift_close",{p_shift_id:s.id,p_notes:"Approved from Shift screen"});setMessage(error?error.message:"Shift closed.");if(!error)load();}
  return <div><div className="page-heading"><div><h2>Cashier Shift & Day Close</h2><p>Opening cash, payment totals, expected cash, actual cash and variance.</p></div></div>{message&&<div className="purchase-message">{message}</div>}
  {(offlineCounts.pending>0||offlineCounts.conflict>0)&&<div className="purchase-message error">Offline queue must be cleared before shift close. Pending {offlineCounts.pending} · Conflicts {offlineCounts.conflict}</div>}
  <div className="settings-grid"><section className="panel"><h3>My Shift</h3>{!mine?<><label>Opening Cash<input type="number" min="0" step="0.01" value={opening} onChange={(e)=>setOpening(e.target.value)}/></label><br/><button className="primary-button" onClick={open}>Open Shift</button></>:<><p>Status: <strong>{mine.status}</strong></p><p>Opened: {new Date(mine.opened_at).toLocaleString("en-IN")}</p><p>Opening Cash: {money.format(mine.opening_cash)}</p>{mine.status==="OPEN"&&<><label>Actual cash physically counted in drawer<input type="number" min="0" step="0.01" value={actual} placeholder="Required before close" onChange={(e)=>setActual(e.target.value)}/></label><p className="muted-text">Do not copy Expected Cash automatically. Actual Cash is the physical count; WineShopPOS compares it with Expected Cash.</p><button className="primary-button" disabled={!navigator.onLine||offlineCounts.pending>0||offlineCounts.conflict>0} onClick={requestClose}>Request Close</button></>}{mine.status==="CLOSE_REQUESTED"&&<div className="purchase-message">Close requested. If Actual Cash was entered incorrectly, correct it in Shift History before approval.</div>}</>}</section>
  <section className="panel"><h3>Close Rule</h3><p>Expected Cash = opening cash + cash sales - cash refunds. Actual Cash must be physically counted; it is never assumed to equal Expected Cash.</p><p>Manager/Admin approves the final close and variance. Any non-zero variance requires explicit confirmation.</p><p>Offline sales must be synchronized or resolved before the device can request close.</p></section></div>
  <section className="panel" style={{marginTop:16}}><h3>Shift History</h3><div className="data-table-wrapper"><SortableTable className="data-table"><thead><tr><th>Opened</th><th>Cashier</th><th>Status</th><th>Cash</th><th>UPI</th><th>Card</th><th>Expected</th><th>Actual</th><th>Difference</th><th data-sort="false">Action</th></tr></thead><tbody>{shifts.map((s)=>{const canRevise=s.status==="CLOSE_REQUESTED"&&(manager||s.cashier_id===profile?.user_id);return <tr key={s.id}><td>{new Date(s.opened_at).toLocaleString("en-IN")}</td><td>{s.cashier_id===profile?.user_id?"Me":s.cashier_id.slice(0,8)}</td><td>{s.status}</td><td>{money.format(s.cash_sales)}</td><td>{money.format(s.upi_sales)}</td><td>{money.format(s.card_sales)}</td><td>{money.format(s.expected_cash)}</td><td>{s.actual_cash==null?"-":money.format(s.actual_cash)}</td><td className={Number(s.cash_difference)<0?"negative":""}>{s.cash_difference==null?"-":money.format(s.cash_difference)}</td><td>{canRevise&&<div className="button-row wrap"><input type="number" min="0" step="0.01" value={corrections[s.id]??String(s.actual_cash??"")} onChange={(e)=>setCorrections((c)=>({...c,[s.id]:e.target.value}))} aria-label="Correct actual cash" style={{maxWidth:120}}/><button type="button" className="secondary-button" onClick={()=>reviseActual(s)}>Update Actual</button></div>}{manager&&s.status==="CLOSE_REQUESTED"&&<button type="button" className="primary-button" onClick={()=>approve(s)} style={{marginTop:canRevise?8:0}}>Approve Close</button>}</td></tr>;})}</tbody></SortableTable></div></section></div>;
}
