import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { useScanner } from "../context/ScannerContext";
import { useShop } from "../context/ShopContext";

export default function StockCount(){const{lastScan,successBeep,errorBeep}=useScanner();const{products,refreshAll}=useShop();const[counts,setCounts]=useState([]);const[items,setItems]=useState([]);const[activeId,setActiveId]=useState("");const[message,setMessage]=useState("");
async function load(){const{data,error}=await supabase.from("stock_counts").select("*").order("created_at",{ascending:false}).limit(30);if(error)setMessage(error.message);else{setCounts(data||[]);const active=(data||[]).find((x)=>["OPEN","SUBMITTED"].includes(x.status));if(active&&!activeId)setActiveId(active.id)}}
async function loadItems(id){if(!id){setItems([]);return}const{data,error}=await supabase.from("stock_count_items").select("*").eq("stock_count_id",id).order("product_id");if(error)setMessage(error.message);else setItems(data||[])}
useEffect(()=>{load()},[]);useEffect(()=>{loadItems(activeId)},[activeId]);
useEffect(()=>{if(!lastScan||!activeId)return;const active=counts.find((c)=>c.id===activeId);if(active?.status!=="OPEN")return;(async()=>{const{data,error}=await supabase.rpc("stock_count_scan",{p_stock_count_id:activeId,p_barcode:lastScan.barcode});if(error){errorBeep();setMessage(error.message)}else{successBeep();setMessage(`${data?.[0]?.product_name||lastScan.barcode}: counted ${data?.[0]?.counted_quantity}`);loadItems(activeId)}})()},[lastScan]);
async function create(){const{data,error}=await supabase.rpc("create_stock_count",{p_notes:"Physical stock count"});setMessage(error?error.message:"Stock count started. Walk the store and scan each bottle.");if(!error){setActiveId(data);await load();await loadItems(data)}}
async function setQty(item,q){const{error}=await supabase.rpc("set_stock_count_quantity",{p_stock_count_id:activeId,p_product_id:item.product_id,p_quantity:Number(q)});if(error)setMessage(error.message);else loadItems(activeId)}
async function markZero(){if(!confirm("Mark every unscanned SKU as counted quantity ZERO? Use only after the physical count is complete."))return;const{data,error}=await supabase.rpc("mark_unseen_stock_count_zero",{p_stock_count_id:activeId});setMessage(error?error.message:`${data} unseen SKU(s) marked zero.`);if(!error)loadItems(activeId)}
async function submit(){const{error}=await supabase.rpc("submit_stock_count",{p_stock_count_id:activeId});setMessage(error?error.message:"Count submitted for approval.");if(!error)load()}
async function approve(){if(!confirm("Approve discrepancies and replace system stock with counted stock?"))return;const{error}=await supabase.rpc("approve_stock_count",{p_stock_count_id:activeId});setMessage(error?error.message:"Stock count approved; inventory adjusted and audited.");if(!error){await Promise.all([load(),refreshAll()])}}
const active=counts.find((c)=>c.id===activeId);const summary=useMemo(()=>items.reduce((a,i)=>{a.total++;if(i.counted_quantity==null)a.unseen++;else if(i.counted_quantity===i.expected_quantity)a.match++;else if(i.counted_quantity<i.expected_quantity)a.short++;else a.excess++;a.diff+=i.counted_quantity==null?0:i.counted_quantity-i.expected_quantity;return a},{total:0,unseen:0,match:0,short:0,excess:0,diff:0}),[items]);
return <div><div className="page-heading"><div><h2>Physical Stock Count</h2><p>Scan every bottle; the global scanner increments the active SKU count.</p></div>{!counts.some((c)=>["OPEN","SUBMITTED"].includes(c.status))&&<button className="primary-button" onClick={create}>Start Stock Count</button>}</div>{message&&<div className="purchase-message">{message}</div>}
<div className="stats-grid"><div className="stat-card"><span>SKUs</span><strong>{summary.total}</strong></div><div className="stat-card"><span>Matched</span><strong>{summary.match}</strong></div><div className="stat-card"><span>Short</span><strong>{summary.short}</strong></div><div className="stat-card"><span>Excess</span><strong>{summary.excess}</strong></div><div className="stat-card"><span>Unseen</span><strong>{summary.unseen}</strong></div></div>
<div className="panel" style={{marginTop:16}}><label>Count Session<select value={activeId} onChange={(e)=>setActiveId(e.target.value)}><option value="">Select</option>{counts.map((c)=><option key={c.id} value={c.id}>{c.count_number} · {c.status}</option>)}</select></label>{active&&<div className="button-row" style={{marginTop:10}}>{active.status==="OPEN"&&<><button className="secondary-button" onClick={markZero}>Mark Unseen = 0</button><button className="primary-button" onClick={submit}>Submit Count</button></>}{active.status==="SUBMITTED"&&<button className="primary-button" onClick={approve}>Approve & Adjust Inventory</button>}</div>}</div>
<section className="panel" style={{marginTop:16}}><div className="data-table-wrapper"><table className="data-table"><thead><tr><th>Product</th><th>System</th><th>Counted</th><th>Difference</th></tr></thead><tbody>{items.map((i)=>{const p=products.find((p)=>p.id===i.product_id);const diff=i.counted_quantity==null?null:i.counted_quantity-i.expected_quantity;return <tr key={i.id}><td>{p?.name||i.product_id.slice(0,8)}</td><td>{i.expected_quantity}</td><td><input type="number" min="0" value={i.counted_quantity??""} placeholder="unseen" disabled={active?.status!=="OPEN"} onChange={(e)=>e.target.value!==""&&setQty(i,e.target.value)}/></td><td className={diff<0?"negative":diff>0?"positive":""}>{diff==null?"-":diff}</td></tr>})}</tbody></table></div></section></div>}
