import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { useShop } from "../context/ShopContext";
import { useAuth } from "../context/AuthContext";
import PageHeader from "../components/ui/PageHeader";
import StatusBadge from "../components/ui/StatusBadge";
import EmptyState from "../components/ui/EmptyState";
export default function Transfers(){const{products,getStock,refreshAll}=useShop();const{profile}=useAuth();const[dest,setDest]=useState([]);const[transfers,setTransfers]=useState([]);const[destination,setDestination]=useState("");const[productId,setProductId]=useState("");const[qty,setQty]=useState(1);const[message,setMessage]=useState("");
async function load(){const[d,t]=await Promise.all([supabase.rpc("available_transfer_destinations"),supabase.from("stock_transfers").select("*,stock_transfer_items(*)").order("created_at",{ascending:false}).limit(150)]);if(d.error||t.error)setMessage("Unable to load transfer queue.");else{setDest(d.data||[]);setTransfers(t.data||[])}}useEffect(()=>{load()},[]);
async function create(e){e.preventDefault();const{error}=await supabase.rpc("create_stock_transfer",{p_destination_shop_id:destination,p_items:[{product_id:productId,quantity:Number(qty)}],p_notes:null});setMessage(error?"Unable to request transfer.":"Transfer requested. Destination must approve before dispatch.");if(!error){setProductId("");setQty(1);load()}}
async function act(fn,id,args={},ok="Transfer updated"){const{error}=await supabase.rpc(fn,{p_transfer_id:id,...args});setMessage(error?`Unable to ${ok.toLowerCase()}.`:ok);if(!error){await Promise.all([load(),refreshAll()])}}
function actions(t){const incoming=t.destination_shop_id===profile?.shop_id;const outgoing=t.source_shop_id===profile?.shop_id;if(t.status==="REQUESTED"&&incoming)return <><button className="primary-button" onClick={()=>act("approve_stock_transfer",t.id,{},"Transfer approved")}>Approve</button><button className="secondary-button" onClick={()=>act("reject_stock_transfer",t.id,{p_note:"Rejected from consolidated transfer screen"},"Transfer rejected")}>Reject</button></>;if(t.status==="REQUESTED"&&outgoing)return <button className="secondary-button" onClick={()=>act("cancel_stock_transfer",t.id,{},"Transfer cancelled")}>Cancel</button>;if(t.status==="APPROVED"&&outgoing)return <button className="primary-button" onClick={()=>act("dispatch_stock_transfer",t.id,{},"Transfer dispatched; source stock deducted")}>Dispatch</button>;if(t.status==="DISPATCHED"&&outgoing)return <button className="secondary-button" onClick={()=>act("mark_stock_transfer_in_transit",t.id,{},"Transfer marked in transit")}>Mark In Transit</button>;if(["DISPATCHED","IN_TRANSIT"].includes(t.status)&&incoming)return <button className="primary-button" onClick={()=>act("receive_stock_transfer",t.id,{},"Transfer received; destination stock increased")}>Receive</button>;if(t.status==="RECEIVED"&&incoming)return <button className="primary-button" onClick={()=>act("complete_stock_transfer",t.id,{},"Transfer completed")}>Complete</button>;return <span className="muted-text">No action</span>}
return <div><PageHeader title="Advanced Stock Transfers" subtitle="Request → approve → dispatch → in transit → receive → complete. Stock changes follow the physical lifecycle." tier="PLUS"/>{message?<div className="purchase-message">{message}</div>:null}<div className="settings-grid"><form className="panel" onSubmit={create}><h3>Request Transfer</h3>{dest.length===0?<EmptyState title="No transfer destination" message="Only shops inside the same organization can be destinations."/>:<div className="settings-fields"><label>Destination<select value={destination} onChange={e=>setDestination(e.target.value)} required><option value="">Select branch</option>{dest.map(d=><option key={d.shop_id} value={d.shop_id}>{d.shop_name}</option>)}</select></label><label>Product<select value={productId} onChange={e=>setProductId(e.target.value)} required><option value="">Select product</option>{products.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name} · stock {getStock(p.id)}</option>)}</select></label><label>Quantity<input type="number" min="1" max={productId?getStock(productId):99999} value={qty} onChange={e=>setQty(e.target.value)} required/></label><button className="primary-button">Request</button></div>}</form><section className="panel"><h3>Transaction Safety</h3><p>Approval reserves permission only. Source stock is deducted only at Dispatch. Destination stock is increased only at Receive.</p><p>Every inventory change is performed inside a database RPC and recorded as a stock movement.</p></section></div><section className="panel" style={{marginTop:16}}><h3>Transfer Queue</h3>{transfers.length===0?<EmptyState title="No transfers" message="Transfer requests will appear here."/>:<div className="data-table-wrapper"><table className="data-table sticky"><thead><tr><th>Created</th><th>Direction</th><th>Qty</th><th>Status</th><th>Dispatched</th><th>Received</th><th>Action</th></tr></thead><tbody>{transfers.map(t=>{const incoming=t.destination_shop_id===profile?.shop_id;return <tr key={t.id}><td>{new Date(t.created_at).toLocaleString("en-IN")}</td><td>{incoming?"INCOMING":"OUTGOING"}</td><td>{(t.stock_transfer_items||[]).reduce((s,i)=>s+Number(i.quantity||0),0)}</td><td><StatusBadge status={t.status}/></td><td>{t.dispatched_at?new Date(t.dispatched_at).toLocaleString("en-IN"):"-"}</td><td>{t.received_at?new Date(t.received_at).toLocaleString("en-IN"):"-"}</td><td><div className="button-row compact">{actions(t)}</div></td></tr>})}</tbody></table></div>}</section></div>}
