import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { useShop } from "../context/ShopContext";
import { useAuth } from "../context/AuthContext";

export default function Transfers(){const{products,getStock,refreshAll}=useShop();const{profile}=useAuth();const[dest,setDest]=useState([]);const[transfers,setTransfers]=useState([]);const[destination,setDestination]=useState("");const[productId,setProductId]=useState("");const[qty,setQty]=useState(1);const[message,setMessage]=useState("");
async function load(){const[d,t]=await Promise.all([supabase.rpc("available_transfer_destinations"),supabase.from("stock_transfers").select(`*,stock_transfer_items(*)`).order("created_at",{ascending:false}).limit(100)]);if(d.error)setMessage(d.error.message);else setDest(d.data||[]);if(t.error)setMessage(t.error.message);else setTransfers(t.data||[])}useEffect(()=>{load()},[]);
async function create(e){e.preventDefault();const{error}=await supabase.rpc("create_stock_transfer",{p_destination_shop_id:destination,p_items:[{product_id:productId,quantity:Number(qty)}],p_notes:null});setMessage(error?error.message:"Transfer requested. Destination branch must approve before stock moves.");if(!error)load()}
async function act(id,action){const fn=action==="approve"?"approve_stock_transfer":action==="reject"?"reject_stock_transfer":"cancel_stock_transfer";const args=action==="reject"?{p_transfer_id:id,p_note:"Rejected from transfer screen"}:{p_transfer_id:id};const{error}=await supabase.rpc(fn,args);setMessage(error?error.message:`Transfer ${action}d.`);if(!error){await Promise.all([load(),refreshAll()])}}
return <div><div className="page-heading"><div><h2>Branch Stock Transfer</h2><p>Transfers are allowed only between shops in the same organization.</p></div></div>{message&&<div className="purchase-message">{message}</div>}
<div className="settings-grid"><form className="panel" onSubmit={create}><h3>Request Transfer Out</h3>{dest.length===0?<p>No other branch is linked to this organization yet. Platform owner must create/link another shop first.</p>:<div className="settings-fields"><label>Destination<select value={destination} onChange={(e)=>setDestination(e.target.value)} required><option value="">Select branch</option>{dest.map((d)=><option key={d.shop_id} value={d.shop_id}>{d.shop_name}</option>)}</select></label><label>Product<select value={productId} onChange={(e)=>setProductId(e.target.value)} required><option value="">Select product</option>{products.filter((p)=>p.active).map((p)=><option key={p.id} value={p.id}>{p.name} · stock {getStock(p.id)}</option>)}</select></label><label>Quantity<input type="number" min="1" max={productId?getStock(productId):99999} value={qty} onChange={(e)=>setQty(e.target.value)} required/></label><button className="primary-button">Request Transfer</button></div>}</form><section className="panel"><h3>Safety Model</h3><p>Source request does not immediately deduct stock. Destination Manager/Admin approves. Approval re-checks source inventory under row lock and posts TRANSFER_OUT + TRANSFER_IN atomically.</p></section></div>
<section className="panel" style={{marginTop:16}}><h3>Transfer Queue</h3><div className="data-table-wrapper"><table className="data-table"><thead><tr><th>Created</th><th>Direction</th><th>Qty</th><th>Status</th><th>Action</th></tr></thead><tbody>{transfers.map((t)=>{const incoming=t.destination_shop_id===profile?.shop_id;return <tr key={t.id}><td>{new Date(t.created_at).toLocaleString("en-IN")}</td><td>{incoming?"INCOMING":"OUTGOING"}</td><td>{(t.stock_transfer_items||[]).reduce((s,i)=>s+i.quantity,0)}</td><td>{t.status}</td><td>{t.status==="REQUESTED"&&incoming?<><button className="primary-button" onClick={()=>act(t.id,"approve")}>Approve</button> <button className="secondary-button" onClick={()=>act(t.id,"reject")}>Reject</button></>:t.status==="REQUESTED"&&!incoming?<button className="secondary-button" onClick={()=>act(t.id,"cancel")}>Cancel</button>:"-"}</td></tr>})}</tbody></table></div></section></div>}
