import { NavLink, Outlet } from "react-router-dom";
import { BarChart3, ClipboardCheck, FileSearch, LayoutDashboard, LogOut, Package, Printer, ReceiptText, RefreshCw, ScanBarcode, Settings, ShoppingBag, ShieldCheck, Truck, Undo2, UsersRound, Warehouse, Wine, ArrowLeftRight, Clock3, Sparkles, TrendingUp } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import OfflineStatus from "./OfflineStatus";
const navigation=[
{path:"/",label:"Dashboard",icon:LayoutDashboard,roles:["ADMIN","MANAGER","CASHIER"]},{path:"/pos",label:"POS Billing",icon:ScanBarcode,roles:["ADMIN","MANAGER","CASHIER"]},{path:"/shifts",label:"Shift / Close",icon:Clock3,roles:["ADMIN","MANAGER","CASHIER"]},{path:"/returns",label:"Returns / Voids",icon:Undo2,roles:["ADMIN","MANAGER","CASHIER"]},{path:"/sales",label:"Sales",icon:ReceiptText,roles:["ADMIN","MANAGER","CASHIER"]},{path:"/offline-queue",label:"Offline Queue",icon:RefreshCw,roles:["ADMIN","MANAGER","CASHIER"]},
{path:"/products",label:"Products",icon:Package,roles:["ADMIN","MANAGER"]},{path:"/inventory",label:"Inventory",icon:Warehouse,roles:["ADMIN","MANAGER"]},{path:"/stock-count",label:"Stock Count",icon:ClipboardCheck,roles:["ADMIN","MANAGER"]},{path:"/purchases",label:"Receive Stock",icon:Truck,roles:["ADMIN","MANAGER"]},{path:"/procurement",label:"Procurement",icon:ShoppingBag,roles:["ADMIN","MANAGER"]},{path:"/price-history",label:"Price History",icon:TrendingUp,roles:["ADMIN","MANAGER"]},{path:"/reorder",label:"Smart Reorder",icon:Sparkles,roles:["ADMIN","MANAGER"]},{path:"/transfers",label:"Transfers",icon:ArrowLeftRight,roles:["ADMIN","MANAGER"]},{path:"/reports",label:"Reports",icon:BarChart3,roles:["ADMIN","MANAGER"]},{path:"/automation",label:"OCR / Automation",icon:FileSearch,roles:["ADMIN","MANAGER"]},{path:"/scanner-settings",label:"Scanner",icon:ScanBarcode,roles:["ADMIN","MANAGER","CASHIER"]},
{path:"/users",label:"Users",icon:UsersRound,roles:["ADMIN"]},{path:"/audit",label:"Audit",icon:ShieldCheck,roles:["ADMIN"]},{path:"/printer-settings",label:"Printer",icon:Printer,roles:["ADMIN"]},{path:"/settings",label:"Settings",icon:Settings,roles:["ADMIN"]},];
export default function Layout(){const{profile,signOut}=useAuth();return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-icon"><Wine size={25}/></div><div><div className="brand-name">WineShop POS</div><div className="brand-subtitle">{profile?.shop_name||"Retail Management"}</div></div></div><nav className="nav-menu">{navigation.filter((i)=>i.roles.includes(profile?.role)).map((i)=>{const Icon=i.icon;return <NavLink key={i.path} to={i.path} end={i.path==="/"} className={({isActive})=>isActive?"nav-item active":"nav-item"}><Icon size={18}/><span>{i.label}</span></NavLink>})}</nav><div className="sidebar-footer"><ShoppingBag size={18}/><div><strong>{profile?.full_name||"User"}</strong><span>{profile?.role||""}</span></div><button title="Sign out" onClick={signOut} className="icon-logout"><LogOut size={17}/></button></div></aside><main className="main-area"><header className="topbar"><div><h1>Wine Shop Management</h1><p>Cloud POS, barcode billing & inventory</p></div><div className="topbar-actions"><OfflineStatus/><div className="user-pill"><div className="avatar">{(profile?.full_name||"U")[0].toUpperCase()}</div><div><strong>{profile?.full_name||"User"}</strong><span>{profile?.role||""}</span></div></div></div></header><div className="page-area"><Outlet/></div></main></div>}
