import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });
const stateLabel = (s) => s === "RESOLVED" ? "VERIFIED" : s === "ACCEPTED_WITH_TOLERANCE" ? "ACCEPTED" : s === "INFORMATIONAL" ? "INFO" : "REVIEW";
const stateTone = (s) => ["RESOLVED","ACCEPTED_WITH_TOLERANCE"].includes(s) ? "ok" : s === "OPEN" ? "review" : "neutral";

export default function PurchaseVerificationEngine({ purchase, ingestion, postedUnits, ocrPackAudit, corrections, viewOriginal }) {
  const [serverState,setServerState]=useState(null),[stateError,setStateError]=useState("");
  const [busy,setBusy]=useState(false),[resolutionType,setResolutionType]=useState(""),[verifiedInvoiceTotal,setVerifiedInvoiceTotal]=useState(""),[reason,setReason]=useState(""),[actionMessage,setActionMessage]=useState("");
  const productValue=Number(purchase?.total||0);
  const landedTotal=purchase?.total_landed_cost==null?productValue:Number(purchase.total_landed_cost||0);
  const extractedTotal=ingestion?.extracted_total==null?null:Number(ingestion.extracted_total);
  const packCorrections=useMemo(()=>(corrections||[]).filter((row)=>{const a=Number(row?.old_values?.units_per_case||0),b=Number(row?.new_values?.units_per_case||0);return Number(row?.quantity_delta||0)!==0||(a&&b&&a!==b);}),[corrections]);
  const unitEvidenceAvailable=ocrPackAudit?.units!=null;
  const unitMatch=unitEvidenceAvailable&&Number(ocrPackAudit.units)===Number(postedUnits);
  const packResolved=unitMatch||packCorrections.length>0;
  const productMasterUpdated=(corrections||[]).some((r)=>r?.updated_product_master);

  async function loadState(){const{data,error}=await supabase.rpc("get_purchase_verification_state",{p_purchase_id:purchase.id});if(error){setStateError(`Verification engine unavailable; showing safe fallback: ${error.message}`);setServerState(null);}else{setStateError("");setServerState(data||null);}}
  useEffect(()=>{if(purchase?.id)loadState();},[purchase?.id]);

  const fallbackVariance=extractedTotal==null?null:Math.abs(extractedTotal-landedTotal);
  const financial=serverState?.financial||{state:extractedTotal==null?"INFORMATIONAL":fallbackVariance<=1?"ACCEPTED_WITH_TOLERANCE":"OPEN",ocr_total:extractedTotal,posted_total:landedTotal,variance:fallbackVariance,auto_accept_amount:1,owner_review_amount:10,resolution_type:null,verified_value:null,reason:null,resolved_at:null};
  const financialOpen=financial.state==="OPEN",packOpen=!packResolved;
  const activeExceptionCount=(financialOpen?1:0)+(packOpen?1:0),overallTone=activeExceptionCount?"review":"ok";
  const transportHandling=Number(purchase.transport_amount||0)+Number(purchase.handling_amount||0)+Number(purchase.loading_unloading_amount||0);
  const discounts=Number(purchase.supplier_discount_amount||0)+Number(purchase.invoice_discount_amount||0);
  const miscRound=Number(purchase.miscellaneous_amount||0)+Number(purchase.rounding_adjustment||0);
  const calculatedLanded=productValue+Number(purchase.freight_amount||0)+transportHandling-discounts+miscRound;
  const goTo=(id)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});

  async function resolveFinancial(){
    if(!resolutionType){setActionMessage("Choose a resolution.");return;}
    if(String(reason||"").trim().length<4){setActionMessage("Enter a short reason for the audit record.");return;}
    setBusy(true);setActionMessage("");
    const{data,error}=await supabase.rpc("resolve_purchase_financial_exception",{p_purchase_id:purchase.id,p_resolution_type:resolutionType,p_verified_invoice_total:resolutionType==="OCR_TOTAL_INCORRECT"?Number(verifiedInvoiceTotal||0):null,p_reason:reason.trim()});
    if(error){setBusy(false);setActionMessage(error.message||"Unable to resolve financial exception.");return;}
    setServerState(data||null);setResolutionType("");setVerifiedInvoiceTotal("");setReason("");setActionMessage("Audited resolution recorded. Purchase and stock values were not changed.");setBusy(false);
  }
  async function reopenFinancial(){const rr=window.prompt("Why are you reopening this financial verification?","Needs further review");if(!rr)return;setBusy(true);const{data,error}=await supabase.rpc("reopen_purchase_financial_exception",{p_purchase_id:purchase.id,p_reason:rr});if(error){setActionMessage(error.message||"Unable to reopen financial verification.");}else{setServerState(data||null);setActionMessage("Financial verification reopened.");}setBusy(false);}

  return <>
    <section className={`panel verification-engine verification-engine--${overallTone}`}>
      <div className="verification-engine-header"><div><span className="verification-engine-kicker">CURRENT BUSINESS STATE</span><h3>{activeExceptionCount?`${activeExceptionCount} action${activeExceptionCount===1?"":"s"} required`:"Purchase verified"}</h3><p>Only unresolved business actions appear as warnings. Historical OCR uncertainty is kept separately below.</p></div><span className={`verification-engine-status verification-engine-status--${overallTone}`}>{activeExceptionCount?"NEEDS ATTENTION":"VERIFIED"}</span></div>
      {stateError?<div className="verification-guidance verification-guidance--review">{stateError}</div>:null}
      <div className="verification-state-grid">
        <button type="button" className={`verification-state-card verification-state-card--${packResolved?"ok":"review"}`} onClick={()=>goTo(packResolved?"correction-history":"purchase-correction")}><span>Pack Quantity</span><strong>{packResolved?(packCorrections.length?"CORRECTED":"VERIFIED"):"REVIEW"}</strong><small>{packCorrections.length?`${packCorrections.length} audited correction applied`:unitMatch?"Receipt and OCR agree":"Action required"}</small></button>
        <button type="button" className="verification-state-card verification-state-card--ok" onClick={()=>goTo("posted-purchase-lines")}><span>Inventory Receipt</span><strong>{purchase.status==="RECEIVED"?"VERIFIED":purchase.status}</strong><small>{postedUnits} bottles posted</small></button>
        <button type="button" className={`verification-state-card verification-state-card--${productMasterUpdated?"ok":"neutral"}`} onClick={()=>goTo("purchase-correction")}><span>Product Master</span><strong>{productMasterUpdated?"UPDATED":"NO CORRECTION"}</strong><small>{productMasterUpdated?"Pack correction synchronized":"No audited Product Master change"}</small></button>
        <button type="button" className={`verification-state-card verification-state-card--${stateTone(financial.state)}`} onClick={()=>goTo("financial-reconciliation")}><span>Financial Total</span><strong>{stateLabel(financial.state)}</strong><small>{financial.state==="OPEN"?`${money.format(Number(financial.variance||0))} to review`:financial.resolution_type?"Audited resolution recorded":financial.state==="ACCEPTED_WITH_TOLERANCE"?`Within ${money.format(Number(financial.auto_accept_amount||0))} tolerance`:"No actionable discrepancy"}</small></button>
      </div>
      <div className="verification-exceptions"><div className="verification-section-title"><span>ACTIVE EXCEPTIONS</span><strong>{activeExceptionCount}</strong></div>
        {!activeExceptionCount?<div className="verification-guidance verification-guidance--ok"><strong>No open exceptions.</strong> Historical OCR evidence is retained below for audit only.</div>:null}
        {financialOpen?<button type="button" className="verification-exception-card" onClick={()=>goTo("financial-reconciliation")}><div><span>Financial Difference</span><strong>{money.format(Number(financial.variance||0))}</strong><small>OCR {money.format(Number(financial.ocr_total||0))} vs WineShopPOS {money.format(Number(financial.posted_total||0))}</small></div><span>Review & Resolve →</span></button>:null}
        {packOpen?<button type="button" className="verification-exception-card" onClick={()=>goTo("purchase-correction")}><div><span>Pack Quantity</span><strong>Needs review</strong><small>OCR and posted pack are not resolved.</small></div><span>Review Pack →</span></button>:null}
      </div>
      <details className="verification-history"><summary>Historical Evidence & Audit</summary><div className="verification-history-grid"><div><span>Original OCR</span><strong>{ingestion?"RETAINED":"NOT LINKED"}</strong></div><div><span>OCR Pack Detection</span><strong>{unitEvidenceAvailable?"CONFIRMED":"NOT DETERMINED"}</strong></div><div><span>OCR Expected Bottles</span><strong>{ocrPackAudit?.units??"Not determined"}</strong></div><div><span>OCR Printed Total</span><strong>{extractedTotal==null?"—":money.format(extractedTotal)}</strong></div><div><span>Audited Corrections</span><strong>{corrections.length}</strong></div><div><span>Pack Resolution</span><strong>{packResolved?"RESOLVED":"OPEN"}</strong></div></div><div className="button-row" style={{marginTop:12}}>{ingestion?<button type="button" className="secondary-button" onClick={viewOriginal}>View Original Invoice</button>:null}<button type="button" className="secondary-button" onClick={()=>goTo("ocr-evidence")}>Open OCR Evidence</button>{corrections.length?<button type="button" className="secondary-button" onClick={()=>goTo("correction-history")}>Open Correction Audit</button>:null}</div></details>
    </section>

    <section id="financial-reconciliation" className="panel verification-target" style={{marginTop:16}}>
      <div className="section-row"><div><h3>Financial Reconciliation</h3><p className="muted-text">Verification decisions are audited separately. This screen never silently changes purchase, stock or FIFO values.</p></div>{ingestion?<button type="button" className="secondary-button" onClick={viewOriginal}>View Original Invoice</button>:null}</div>
      <div className="financial-reconciliation-grid"><div><span>Product Value</span><strong>{money.format(productValue)}</strong></div><div><span>+ Freight</span><strong>{money.format(Number(purchase.freight_amount||0))}</strong></div><div><span>+ Transport / Handling</span><strong>{money.format(transportHandling)}</strong></div><div><span>− Discounts</span><strong>{money.format(discounts)}</strong></div><div><span>+ Misc / Round</span><strong>{money.format(miscRound)}</strong></div><div className="financial-reconciliation-total"><span>= WineShopPOS Landed Total</span><strong>{money.format(calculatedLanded)}</strong></div><div><span>Original OCR Total</span><strong>{extractedTotal==null?"—":money.format(extractedTotal)}</strong></div><div className={financialOpen?"financial-reconciliation-review":"financial-reconciliation-ok"}><span>Verification Difference</span><strong>{financial.variance==null?"—":money.format(Number(financial.variance))}</strong></div></div>
      <div className="verification-policy-strip"><span>Auto accepted ≤ {money.format(Number(financial.auto_accept_amount||1))}</span><span>Manager review ≤ {money.format(Number(financial.owner_review_amount||10))}</span><span>Larger variance requires Admin</span></div>
      {financialOpen?<div className="financial-resolution-box"><h4>Resolve this active exception</h4><p>Choose what you verified from the original supplier invoice. The decision is audited; purchase and inventory values remain unchanged.</p><div className="financial-resolution-options"><label className={resolutionType==="ACCEPT_SMALL_VARIANCE"?"active":""}><input type="radio" name="financial-resolution" value="ACCEPT_SMALL_VARIANCE" checked={resolutionType==="ACCEPT_SMALL_VARIANCE"} onChange={(e)=>setResolutionType(e.target.value)}/><span><strong>Accept reviewed variance</strong><small>Use when the invoice is correct and the small difference is immaterial/rounding. Current difference: {money.format(Number(financial.variance||0))}.</small></span></label><label className={resolutionType==="OCR_TOTAL_INCORRECT"?"active":""}><input type="radio" name="financial-resolution" value="OCR_TOTAL_INCORRECT" checked={resolutionType==="OCR_TOTAL_INCORRECT"} onChange={(e)=>setResolutionType(e.target.value)}/><span><strong>OCR invoice total is incorrect</strong><small>Enter the verified total visible on the original invoice. Original OCR stays in history.</small></span></label></div>{resolutionType==="OCR_TOTAL_INCORRECT"?<label className="financial-resolution-field">Verified Invoice Total<input type="number" min="0" step="0.01" value={verifiedInvoiceTotal} onChange={(e)=>setVerifiedInvoiceTotal(e.target.value)} placeholder={landedTotal.toFixed(2)}/></label>:null}<label className="financial-resolution-field">Resolution Reason<input value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="What did you verify on the original invoice?"/></label>{actionMessage?<div className="purchase-message">{actionMessage}</div>:null}<div className="button-row"><button type="button" className="primary-button" disabled={busy||!resolutionType} onClick={resolveFinancial}>{busy?"Saving...":"Record Audited Resolution"}</button><button type="button" className="secondary-button" disabled={busy} onClick={()=>{setResolutionType("");setVerifiedInvoiceTotal("");setReason("");setActionMessage("");}}>Leave Open</button></div></div>:<div className="verification-guidance verification-guidance--ok"><strong>Financial verification is closed.</strong> {financial.resolution_type?`Resolution: ${String(financial.resolution_type).replaceAll("_"," ")}. ${financial.reason||""}`:financial.state==="ACCEPTED_WITH_TOLERANCE"?`Difference is inside the automatic ${money.format(Number(financial.auto_accept_amount||1))} tolerance.`:"No actionable discrepancy remains."}{financial.resolution_type?<div style={{marginTop:10}}><button type="button" className="secondary-button" disabled={busy} onClick={reopenFinancial}>Reopen Financial Review</button></div>:null}{actionMessage?<div style={{marginTop:8}}>{actionMessage}</div>:null}</div>}
    </section>
  </>;
}
