import { app } from "@azure/functions";
import { DefaultAzureCredential } from "@azure/identity";
import { BlobSASPermissions,BlobServiceClient,SASProtocol,generateBlobSASQueryParameters } from "@azure/storage-blob";
import { createClient } from "@supabase/supabase-js";
import crypto from "node:crypto";
const SUPABASE_URL=process.env.SUPABASE_URL;const SUPABASE_KEY=process.env.SUPABASE_PUBLISHABLE_KEY;const STORAGE_ACCOUNT=process.env.INVOICE_STORAGE_ACCOUNT;const STORAGE_CONTAINER=process.env.INVOICE_STORAGE_CONTAINER||"invoice-documents";const BUSINESS_TIMEZONE=process.env.BUSINESS_TIMEZONE||"Asia/Kolkata";const MAX_STORE_BYTES=Number(process.env.INVOICE_MAX_STORE_BYTES||30*1024*1024);
function json(status,body){return{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"},jsonBody:body};}
function tokenFrom(request){return String(request.headers.get("authorization")||"").match(/^Bearer\s+(.+)$/i)?.[1]||"";}
function clients(token){if(!SUPABASE_URL||!SUPABASE_KEY)throw new Error("Invoice Supabase configuration incomplete.");const auth=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const caller=createClient(SUPABASE_URL,SUPABASE_KEY,{accessToken:async()=>token,auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});return{auth,caller};}
async function authorizedCaller(request){const token=tokenFrom(request);if(!token)throw Object.assign(new Error("AUTH_REQUIRED"),{statusCode:401});const{auth,caller}=clients(token);const{data:u,error:ue}=await auth.auth.getUser(token);if(ue||!u?.user?.id)throw Object.assign(new Error("AUTH_REQUIRED"),{statusCode:401});const{data:p,error:pe}=await caller.from("profiles").select("id,shop_id,role,active").eq("id",u.user.id).single();if(pe||!p?.active||!p?.shop_id||!["ADMIN","MANAGER"].includes(p.role))throw Object.assign(new Error("ACCESS_DENIED"),{statusCode:403});return{user:u.user,profile:p,caller};}
function storage(){if(!STORAGE_ACCOUNT)throw new Error("Invoice Blob storage not configured.");return new BlobServiceClient(`https://${STORAGE_ACCOUNT}.blob.core.windows.net`,new DefaultAzureCredential());}
function dateParts(date=new Date()){const f=new Intl.DateTimeFormat("en-US",{timeZone:BUSINESS_TIMEZONE,year:"numeric",month:"2-digit",day:"2-digit"});const p=Object.fromEntries(f.formatToParts(date).map(x=>[x.type,x.value]));return{year:p.year,month:p.month,mmddyyyy:`${p.month}${p.day}${p.year}`};}
function safeName(name){const raw=String(name||"invoice").trim().replace(/[/\\]/g,"_");const dot=raw.lastIndexOf(".");const base=(dot>0?raw.slice(0,dot):raw).replace(/[^a-zA-Z0-9._ -]+/g,"_").replace(/\s+/g," ").trim().slice(0,140)||"invoice";const ext=dot>0?raw.slice(dot+1).replace(/[^a-zA-Z0-9]+/g,"").slice(0,10).toLowerCase():"";return{base,ext};}
function storedName(name,date){const{base,ext}=safeName(name);const{mmddyyyy}=dateParts(date);return`${base}_${mmddyyyy}${ext?`.${ext}`:""}`;}
function publicError(e){const s=Number(e?.statusCode||0);if(s)return{status:s,message:s===401?"Sign in again.":"Invoice access is not allowed."};return{status:503,message:"Invoice document storage is temporarily unavailable. Existing POS/OCR remains available."};}
app.http("invoice-storage-health",{methods:["GET"],authLevel:"anonymous",route:"invoice/storage-health",handler:async(_r,c)=>{try{await storage().getContainerClient(STORAGE_CONTAINER).getProperties();return json(200,{ok:true,blobAccessOk:true,container:STORAGE_CONTAINER});}catch(e){c.error("Invoice storage health failed",{message:String(e?.message||"").slice(0,180)});return json(503,{ok:false,blobAccessOk:false,error:"Invoice Blob access is not ready."});}}});
app.http("invoice-manual-store",{methods:["POST","OPTIONS"],authLevel:"anonymous",route:"invoice/manual-store",handler:async(r,c)=>{if(r.method==="OPTIONS")return json(200,{ok:true});try{const{user,profile,caller}=await authorizedCaller(r);const b=await r.json();const fileName=String(b?.file_name||"").trim();const contentType=String(b?.content_type||"application/octet-stream");const base64=String(b?.content_base64||"");if(!fileName||!base64)return json(400,{error:"Invoice file content is required."});const bytes=Buffer.from(base64,"base64");if(!bytes.length)return json(400,{error:"Invoice file is empty."});if(bytes.length>MAX_STORE_BYTES)return json(400,{error:"Invoice file exceeds document-storage limit."});const sha256=crypto.createHash("sha256").update(bytes).digest("hex");const{data:existing,error:de}=await caller.from("invoice_ingestions").select("id,review_status,purchase_id,stored_file_name,received_at").eq("shop_id",profile.shop_id).eq("sha256",sha256).order("received_at",{ascending:false}).limit(1);if(de)throw de;if(existing?.[0])return json(200,{ok:true,duplicate:true,ingestion_id:existing[0].id,existing_status:existing[0].review_status,existing_purchase_id:existing[0].purchase_id,existing_file_name:existing[0].stored_file_name});const id=crypto.randomUUID();const receivedAt=new Date();const parts=dateParts(receivedAt);const finalName=storedName(fileName,receivedAt);const blobPath=`${profile.shop_id}/${parts.year}/${parts.month}/${id}/${finalName}`;const blob=storage().getContainerClient(STORAGE_CONTAINER).getBlockBlobClient(blobPath);await blob.uploadData(bytes,{blobHTTPHeaders:{blobContentType:contentType,blobContentDisposition:`inline; filename="${finalName.replaceAll('"','')}"`}});const{error:ie}=await caller.from("invoice_ingestions").insert({id,shop_id:profile.shop_id,source:"MANUAL",source_identity:user.email||null,original_file_name:fileName,stored_file_name:finalName,blob_container:STORAGE_CONTAINER,blob_path:blobPath,content_type:contentType,size_bytes:bytes.length,sha256,received_at:receivedAt.toISOString(),ocr_status:"STORED",review_status:"NEEDS_REVIEW",created_by:user.id});if(ie){try{await blob.deleteIfExists();}catch{}throw ie;}return json(200,{ok:true,duplicate:false,ingestion_id:id,stored_file_name:finalName,received_at:receivedAt.toISOString()});}catch(e){const s=publicError(e);c.error("Manual invoice store failed",{message:String(e?.message||"").slice(0,180)});return json(s.status,{error:s.message});}}});
app.http("invoice-read-url",{methods:["POST","OPTIONS"],authLevel:"anonymous",route:"invoice/read-url",handler:async(r,c)=>{if(r.method==="OPTIONS")return json(200,{ok:true});try{const{caller}=await authorizedCaller(r);const b=await r.json();const id=String(b?.ingestion_id||"").trim();if(!id)return json(400,{error:"Invoice ingestion ID is required."});const{data:i,error}=await caller.from("invoice_ingestions").select("id,blob_container,blob_path,stored_file_name").eq("id",id).single();if(error||!i)throw Object.assign(new Error("ACCESS_DENIED"),{statusCode:403});const svc=storage();const startsOn=new Date(Date.now()-60000),expiresOn=new Date(Date.now()+5*60000);const key=await svc.getUserDelegationKey(startsOn,expiresOn);const sas=generateBlobSASQueryParameters({containerName:i.blob_container,blobName:i.blob_path,permissions:BlobSASPermissions.parse("r"),startsOn,expiresOn,protocol:SASProtocol.Https},key,STORAGE_ACCOUNT).toString();const path=i.blob_path.split("/").map(encodeURIComponent).join("/");return json(200,{ok:true,expires_at:expiresOn.toISOString(),url:`https://${STORAGE_ACCOUNT}.blob.core.windows.net/${encodeURIComponent(i.blob_container)}/${path}?${sas}`});}catch(e){const s=publicError(e);c.error("Invoice read-url failed",{message:String(e?.message||"").slice(0,180)});return json(s.status,{error:s.message});}}});
